// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     ffrwd:av@0.19.0
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:random@0.2.0
//     wasi:cli@0.2.0
//     ffrwd:av-go@0.2.0

package main

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/export_ffrwd_av_node"
	"wit_component/ffrwd_av_node"
	"wit_component/ffrwd_av_node_tick"
	"wit_component/ffrwd_av_node_types"
	"wit_component/ffrwd_av_types"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, (18 * 4), 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport ffrwd:av/node@0.19.0#describe
func wasm_export_ffrwd_av_node_describe() uintptr {

	pinner := &syncExportPinner
	result := export_ffrwd_av_node.Describe()
	utf8 := unsafe.Pointer(unsafe.StringData((result).Name))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len((result).Name)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
	utf80 := unsafe.Pointer(unsafe.StringData((result).Version))
	pinner.Pin(utf80)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (3 * 4))) = uint32(uint32(len((result).Version)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uintptr(uintptr(utf80)))
	utf81 := unsafe.Pointer(unsafe.StringData((result).ParamsSchema))
	pinner.Pin(utf81)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (5 * 4))) = uint32(uint32(len((result).ParamsSchema)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (4 * 4))) = uint32(uintptr(uintptr(utf81)))
	utf82 := unsafe.Pointer(unsafe.StringData((result).RowsSchema))
	pinner.Pin(utf82)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (7 * 4))) = uint32(uint32(len((result).RowsSchema)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (6 * 4))) = uint32(uintptr(uintptr(utf82)))
	slice := (result).PixelFormats
	length := uint32(len(slice))
	result4 := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result4, index*(2*4))
		utf83 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf83)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf83)))

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (9 * 4))) = uint32(length)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 * 4))) = uint32(uintptr(uintptr(result4)))
	slice6 := (result).SampleFormats
	length8 := uint32(len(slice6))
	result7 := witRuntime.Allocate(pinner, uintptr(length8*(2*4)), 4)
	for index, element := range slice6 {
		base := unsafe.Add(result7, index*(2*4))
		utf85 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf85)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf85)))

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (11 * 4))) = uint32(length8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (10 * 4))) = uint32(uintptr(uintptr(result7)))
	data := unsafe.Pointer(unsafe.SliceData((result).SampleRates))
	pinner.Pin(data)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (13 * 4))) = uint32(uint32(len((result).SampleRates)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (12 * 4))) = uint32(uintptr(uintptr(data)))
	data9 := unsafe.Pointer(unsafe.SliceData((result).ChannelCounts))
	pinner.Pin(data9)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (15 * 4))) = uint32(uint32(len((result).ChannelCounts)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (14 * 4))) = uint32(uintptr(uintptr(data9)))
	slice11 := (result).RowsLanguage
	length13 := uint32(len(slice11))
	result12 := witRuntime.Allocate(pinner, uintptr(length13*(2*4)), 4)
	for index, element := range slice11 {
		base := unsafe.Add(result12, index*(2*4))
		utf810 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf810)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf810)))

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (17 * 4))) = uint32(length13)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 * 4))) = uint32(uintptr(uintptr(result12)))
	return exportReturnArea

}

//go:wasmexport cabi_post_ffrwd:av/node@0.19.0#describe
func wasm_export_post_return_ffrwd_av_node_describe(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport ffrwd:av/node@0.19.0#shape
func wasm_export_ffrwd_av_node_shape(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32) uintptr {

	pinner := &syncExportPinner
	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	result := make([]string, 0, arg3)
	for index := 0; index < int(arg3); index++ {
		base := unsafe.Add(unsafe.Pointer(arg2), index*(2*4))
		value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

		result = append(result, value0)
	}

	witRuntime.Unpin()
	result1 := export_ffrwd_av_node.Shape(value, result)

	switch result1.Tag() {
	case witTypes.ResultOk:
		payload := result1.Ok()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))
		slice20 := (payload).Inputs
		length22 := uint32(len(slice20))
		result21 := witRuntime.Allocate(pinner, uintptr(length22*(72+28*4)), 8)
		for index, element := range slice20 {
			base := unsafe.Add(result21, index*(72+28*4))
			utf8 := unsafe.Pointer(unsafe.StringData((element).Name))
			pinner.Pin(utf8)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).Name)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = int8(int32((element).Kind))
			var result2 int32
			if (element).Required {
				result2 = 1
			} else {
				result2 = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (1 + 2*4))) = int8(result2)
			var result3 int32
			if (element).Many {
				result3 = 1
			} else {
				result3 = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (2 + 2*4))) = int8(result3)

			switch (element).Pairing.Tag() {
			case ffrwd_av_node_types.PairingLockstep:

				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = int8(int32(0))

			case ffrwd_av_node_types.PairingHold:
				payload := (element).Pairing.Hold()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = int8(int32(1))

				switch (payload).Anchor.Tag() {
				case ffrwd_av_node_types.AnchorSharedClock:

					*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4))) = int8(int32(0))

				case ffrwd_av_node_types.AnchorFirstFrame:

					*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4))) = int8(int32(1))

				case ffrwd_av_node_types.AnchorTagged:
					payload := (payload).Anchor.Tagged()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4))) = int8(int32(2))
					utf84 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf84)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 4*4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 3*4))) = uint32(uintptr(uintptr(utf84)))

				default:
					panic("unreachable")
				}
				*(*float64)(unsafe.Add(unsafe.Pointer(base), (24 + 4*4))) = (payload).Lead

				switch (payload).Linger.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (32 + 4*4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Linger.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (32 + 4*4))) = int8(int32(1))
					*(*float64)(unsafe.Add(unsafe.Pointer(base), (40 + 4*4))) = payload

				default:
					panic("unreachable")
				}

				switch (payload).Timeout.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (48 + 4*4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Timeout.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (48 + 4*4))) = int8(int32(1))
					*(*float64)(unsafe.Add(unsafe.Pointer(base), (56 + 4*4))) = payload

				default:
					panic("unreachable")
				}

				switch (payload).Group.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (64 + 4*4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Group.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (64 + 4*4))) = int8(int32(1))
					utf85 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf85)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 6*4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 5*4))) = uint32(uintptr(uintptr(utf85)))

				default:
					panic("unreachable")
				}

				switch (payload).PortParam.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (64 + 7*4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).PortParam.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (64 + 7*4))) = int8(int32(1))
					utf86 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf86)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 9*4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 8*4))) = uint32(uintptr(uintptr(utf86)))

				default:
					panic("unreachable")
				}

			case ffrwd_av_node_types.PairingInterval:
				payload := (element).Pairing.Interval()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = int8(int32(2))

				switch (payload).Latency.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Latency.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4))) = int8(int32(1))
					*(*float64)(unsafe.Add(unsafe.Pointer(base), (24 + 2*4))) = payload

				default:
					panic("unreachable")
				}
				*(*float64)(unsafe.Add(unsafe.Pointer(base), (32 + 2*4))) = (payload).Ahead

			case ffrwd_av_node_types.PairingArrival:

				*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = int8(int32(3))

			default:
				panic("unreachable")
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (64 + 10*4))) = int8(int32((element).Rows))
			*(*int32)(unsafe.Add(unsafe.Pointer(base), (68 + 10*4))) = int32((element).Window)
			*(*int32)(unsafe.Add(unsafe.Pointer(base), (72 + 10*4))) = int32((element).Stride)
			slice := ((element).Accepts).PixelFormats
			length := uint32(len(slice))
			result8 := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
			for index, element := range slice {
				base := unsafe.Add(result8, index*(2*4))
				utf87 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf87)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf87)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (72 + 12*4))) = uint32(length)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (72 + 11*4))) = uint32(uintptr(uintptr(result8)))
			slice10 := ((element).Accepts).SampleFormats
			length12 := uint32(len(slice10))
			result11 := witRuntime.Allocate(pinner, uintptr(length12*(2*4)), 4)
			for index, element := range slice10 {
				base := unsafe.Add(result11, index*(2*4))
				utf89 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf89)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf89)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (72 + 14*4))) = uint32(length12)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (72 + 13*4))) = uint32(uintptr(uintptr(result11)))
			data := unsafe.Pointer(unsafe.SliceData(((element).Accepts).SampleRates))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (72 + 16*4))) = uint32(uint32(len(((element).Accepts).SampleRates)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (72 + 15*4))) = uint32(uintptr(uintptr(data)))
			data13 := unsafe.Pointer(unsafe.SliceData(((element).Accepts).ChannelCounts))
			pinner.Pin(data13)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (72 + 18*4))) = uint32(uint32(len(((element).Accepts).ChannelCounts)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (72 + 17*4))) = uint32(uintptr(uintptr(data13)))
			slice15 := ((element).Accepts).Codecs
			length17 := uint32(len(slice15))
			result16 := witRuntime.Allocate(pinner, uintptr(length17*(2*4)), 4)
			for index, element := range slice15 {
				base := unsafe.Add(result16, index*(2*4))
				utf814 := unsafe.Pointer(unsafe.StringData(element))
				pinner.Pin(utf814)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf814)))

			}

			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (72 + 20*4))) = uint32(length17)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (72 + 19*4))) = uint32(uintptr(uintptr(result16)))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (72 + 21*4))) = int8(int32(((element).Accepts).Wants))

			switch ((element).Accepts).Like.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (72 + 22*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := ((element).Accepts).Like.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (72 + 22*4))) = int8(int32(1))
				utf818 := unsafe.Pointer(unsafe.StringData(payload))
				pinner.Pin(utf818)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (72 + 24*4))) = uint32(uint32(len(payload)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (72 + 23*4))) = uint32(uintptr(uintptr(utf818)))

			default:
				panic("unreachable")
			}

			switch (element).Schema.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (72 + 25*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (element).Schema.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (72 + 25*4))) = int8(int32(1))
				utf819 := unsafe.Pointer(unsafe.StringData(payload))
				pinner.Pin(utf819)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (72 + 27*4))) = uint32(uint32(len(payload)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (72 + 26*4))) = uint32(uintptr(uintptr(utf819)))

			default:
				panic("unreachable")
			}

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(length22)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(result21)))
		slice43 := (payload).Outputs
		length45 := uint32(len(slice43))
		result44 := witRuntime.Allocate(pinner, uintptr(length45*(80+22*4)), 8)
		for index, element := range slice43 {
			base := unsafe.Add(result44, index*(80+22*4))
			utf823 := unsafe.Pointer(unsafe.StringData((element).Name))
			pinner.Pin(utf823)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).Name)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf823)))
			*(*int8)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = int8(int32((element).Kind))

			switch (element).Format.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (element).Format.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (3 * 4))) = int8(int32(1))

				switch payload.Tag() {
				case ffrwd_av_node_types.OutputFormatVideo:
					payload := payload.Video()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = int8(int32(0))
					*(*int32)(unsafe.Add(unsafe.Pointer(base), (5 * 4))) = int32((payload).Width)
					*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 5*4))) = int32((payload).Height)
					utf824 := unsafe.Pointer(unsafe.StringData((payload).PixFmt))
					pinner.Pin(utf824)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 6*4))) = uint32(uint32(len((payload).PixFmt)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 5*4))) = uint32(uintptr(uintptr(utf824)))

					switch (payload).Color.Tag() {
					case witTypes.OptionNone:
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 7*4))) = int8(int32(0))

					case witTypes.OptionSome:
						payload := (payload).Color.Some()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 7*4))) = int8(int32(1))
						utf825 := unsafe.Pointer(unsafe.StringData((payload).Range))
						pinner.Pin(utf825)
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 9*4))) = uint32(uint32(len((payload).Range)))
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 8*4))) = uint32(uintptr(uintptr(utf825)))
						utf826 := unsafe.Pointer(unsafe.StringData((payload).Primaries))
						pinner.Pin(utf826)
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 11*4))) = uint32(uint32(len((payload).Primaries)))
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 10*4))) = uint32(uintptr(uintptr(utf826)))
						utf827 := unsafe.Pointer(unsafe.StringData((payload).Trc))
						pinner.Pin(utf827)
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 13*4))) = uint32(uint32(len((payload).Trc)))
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 12*4))) = uint32(uintptr(uintptr(utf827)))
						utf828 := unsafe.Pointer(unsafe.StringData((payload).Space))
						pinner.Pin(utf828)
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 15*4))) = uint32(uint32(len((payload).Space)))
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 14*4))) = uint32(uintptr(uintptr(utf828)))

					default:
						panic("unreachable")
					}

				case ffrwd_av_node_types.OutputFormatAudio:
					payload := payload.Audio()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = int8(int32(1))
					*(*int32)(unsafe.Add(unsafe.Pointer(base), (5 * 4))) = int32((payload).SampleRate)
					*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 5*4))) = int32((payload).Channels)
					utf829 := unsafe.Pointer(unsafe.StringData((payload).SampleFmt))
					pinner.Pin(utf829)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 6*4))) = uint32(uint32(len((payload).SampleFmt)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 5*4))) = uint32(uintptr(uintptr(utf829)))

					switch (payload).ChannelLayout.Tag() {
					case witTypes.OptionNone:
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 7*4))) = int8(int32(0))

					case witTypes.OptionSome:
						payload := (payload).ChannelLayout.Some()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 7*4))) = int8(int32(1))
						utf830 := unsafe.Pointer(unsafe.StringData(payload))
						pinner.Pin(utf830)
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 9*4))) = uint32(uint32(len(payload)))
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 8*4))) = uint32(uintptr(uintptr(utf830)))

					default:
						panic("unreachable")
					}

				case ffrwd_av_node_types.OutputFormatData:
					payload := payload.Data()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = int8(int32(2))
					utf831 := unsafe.Pointer(unsafe.StringData(payload))
					pinner.Pin(utf831)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (6 * 4))) = uint32(uint32(len(payload)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (5 * 4))) = uint32(uintptr(uintptr(utf831)))

				case ffrwd_av_node_types.OutputFormatPackets:
					payload := payload.Packets()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = int8(int32(3))
					utf832 := unsafe.Pointer(unsafe.StringData((payload).Codec))
					pinner.Pin(utf832)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (6 * 4))) = uint32(uint32(len((payload).Codec)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (5 * 4))) = uint32(uintptr(uintptr(utf832)))
					*(*int32)(unsafe.Add(unsafe.Pointer(base), (7 * 4))) = ((payload).TimeBase).Num
					*(*int32)(unsafe.Add(unsafe.Pointer(base), (4 + 7*4))) = ((payload).TimeBase).Den

					switch (payload).Format.Tag() {
					case ffrwd_av_types.CodedFormatVideo:
						payload := (payload).Format.Video()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 7*4))) = int8(int32(0))
						*(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 8*4))) = int32((payload).Width)
						*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 8*4))) = int32((payload).Height)

						switch (payload).SampleAspectRatio.Tag() {
						case witTypes.OptionNone:
							*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 8*4))) = int8(int32(0))

						case witTypes.OptionSome:
							payload := (payload).SampleAspectRatio.Some()
							*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 8*4))) = int8(int32(1))
							*(*int32)(unsafe.Add(unsafe.Pointer(base), (20 + 8*4))) = (payload).Num
							*(*int32)(unsafe.Add(unsafe.Pointer(base), (24 + 8*4))) = (payload).Den

						default:
							panic("unreachable")
						}

						switch (payload).Color.Tag() {
						case witTypes.OptionNone:
							*(*int8)(unsafe.Add(unsafe.Pointer(base), (24 + 9*4))) = int8(int32(0))

						case witTypes.OptionSome:
							payload := (payload).Color.Some()
							*(*int8)(unsafe.Add(unsafe.Pointer(base), (24 + 9*4))) = int8(int32(1))
							utf833 := unsafe.Pointer(unsafe.StringData((payload).Range))
							pinner.Pin(utf833)
							*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 11*4))) = uint32(uint32(len((payload).Range)))
							*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 10*4))) = uint32(uintptr(uintptr(utf833)))
							utf834 := unsafe.Pointer(unsafe.StringData((payload).Primaries))
							pinner.Pin(utf834)
							*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 13*4))) = uint32(uint32(len((payload).Primaries)))
							*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 12*4))) = uint32(uintptr(uintptr(utf834)))
							utf835 := unsafe.Pointer(unsafe.StringData((payload).Trc))
							pinner.Pin(utf835)
							*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 15*4))) = uint32(uint32(len((payload).Trc)))
							*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 14*4))) = uint32(uintptr(uintptr(utf835)))
							utf836 := unsafe.Pointer(unsafe.StringData((payload).Space))
							pinner.Pin(utf836)
							*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 17*4))) = uint32(uint32(len((payload).Space)))
							*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 16*4))) = uint32(uintptr(uintptr(utf836)))

						default:
							panic("unreachable")
						}

					case ffrwd_av_types.CodedFormatAudio:
						payload := (payload).Format.Audio()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 7*4))) = int8(int32(1))
						*(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 8*4))) = int32((payload).SampleRate)
						*(*int32)(unsafe.Add(unsafe.Pointer(base), (12 + 8*4))) = int32((payload).Channels)

						switch (payload).ChannelLayout.Tag() {
						case witTypes.OptionNone:
							*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 8*4))) = int8(int32(0))

						case witTypes.OptionSome:
							payload := (payload).ChannelLayout.Some()
							*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 8*4))) = int8(int32(1))
							utf837 := unsafe.Pointer(unsafe.StringData(payload))
							pinner.Pin(utf837)
							*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 10*4))) = uint32(uint32(len(payload)))
							*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 9*4))) = uint32(uintptr(uintptr(utf837)))

						default:
							panic("unreachable")
						}

					case ffrwd_av_types.CodedFormatData:

						*(*int8)(unsafe.Add(unsafe.Pointer(base), (8 + 7*4))) = int8(int32(2))

					default:
						panic("unreachable")
					}
					data38 := unsafe.Pointer(unsafe.SliceData((payload).Extradata))
					pinner.Pin(data38)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 19*4))) = uint32(uint32(len((payload).Extradata)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 18*4))) = uint32(uintptr(uintptr(data38)))

					switch (payload).Profile.Tag() {
					case witTypes.OptionNone:
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (24 + 20*4))) = int8(int32(0))

					case witTypes.OptionSome:
						payload := (payload).Profile.Some()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (24 + 20*4))) = int8(int32(1))
						*(*int32)(unsafe.Add(unsafe.Pointer(base), (28 + 20*4))) = payload

					default:
						panic("unreachable")
					}

					switch (payload).Level.Tag() {
					case witTypes.OptionNone:
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (32 + 20*4))) = int8(int32(0))

					case witTypes.OptionSome:
						payload := (payload).Level.Some()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (32 + 20*4))) = int8(int32(1))
						*(*int32)(unsafe.Add(unsafe.Pointer(base), (36 + 20*4))) = payload

					default:
						panic("unreachable")
					}

				case ffrwd_av_node_types.OutputFormatLike:
					payload := payload.Like()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (4 * 4))) = int8(int32(4))
					utf839 := unsafe.Pointer(unsafe.StringData((payload).Port))
					pinner.Pin(utf839)
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (6 * 4))) = uint32(uint32(len((payload).Port)))
					*(*uint32)(unsafe.Add(unsafe.Pointer(base), (5 * 4))) = uint32(uintptr(uintptr(utf839)))

					switch (payload).PixelFormat.Tag() {
					case witTypes.OptionNone:
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (7 * 4))) = int8(int32(0))

					case witTypes.OptionSome:
						payload := (payload).PixelFormat.Some()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (7 * 4))) = int8(int32(1))
						utf840 := unsafe.Pointer(unsafe.StringData(payload))
						pinner.Pin(utf840)
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (9 * 4))) = uint32(uint32(len(payload)))
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 * 4))) = uint32(uintptr(uintptr(utf840)))

					default:
						panic("unreachable")
					}

					switch (payload).SampleFormat.Tag() {
					case witTypes.OptionNone:
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (10 * 4))) = int8(int32(0))

					case witTypes.OptionSome:
						payload := (payload).SampleFormat.Some()
						*(*int8)(unsafe.Add(unsafe.Pointer(base), (10 * 4))) = int8(int32(1))
						utf841 := unsafe.Pointer(unsafe.StringData(payload))
						pinner.Pin(utf841)
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (12 * 4))) = uint32(uint32(len(payload)))
						*(*uint32)(unsafe.Add(unsafe.Pointer(base), (11 * 4))) = uint32(uintptr(uintptr(utf841)))

					default:
						panic("unreachable")
					}

				default:
					panic("unreachable")
				}

			default:
				panic("unreachable")
			}

			switch (element).TimeBase.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (40 + 20*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (element).TimeBase.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (40 + 20*4))) = int8(int32(1))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (44 + 20*4))) = (payload).Num
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (48 + 20*4))) = (payload).Den

			default:
				panic("unreachable")
			}
			*(*float64)(unsafe.Add(unsafe.Pointer(base), (56 + 20*4))) = (element).Latency

			switch (element).Schema.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (64 + 20*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (element).Schema.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (64 + 20*4))) = int8(int32(1))
				utf842 := unsafe.Pointer(unsafe.StringData(payload))
				pinner.Pin(utf842)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 22*4))) = uint32(uint32(len(payload)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 21*4))) = uint32(uintptr(uintptr(utf842)))

			default:
				panic("unreachable")
			}

			switch (element).Row.Tag() {
			case witTypes.OptionNone:
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (64 + 23*4))) = int8(int32(0))

			case witTypes.OptionSome:
				payload := (element).Row.Some()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (64 + 23*4))) = int8(int32(1))
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (68 + 23*4))) = int32(payload)

			default:
				panic("unreachable")
			}

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (4 * 4))) = uint32(length45)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (3 * 4))) = uint32(uintptr(uintptr(result44)))

		switch (payload).Clock.Tag() {
		case ffrwd_av_node_types.ClockInput:
			payload := (payload).Clock.Input()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (5 * 4))) = int8(int32(0))
			utf846 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf846)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (7 * 4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (6 * 4))) = uint32(uintptr(uintptr(utf846)))

		case ffrwd_av_node_types.ClockRate:
			payload := (payload).Clock.Rate()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (5 * 4))) = int8(int32(1))
			*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (6 * 4))) = (payload).Num
			*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (4 + 6*4))) = (payload).Den

		case ffrwd_av_node_types.ClockRateOf:
			payload := (payload).Clock.RateOf()
			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (5 * 4))) = int8(int32(2))
			utf847 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf847)
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (7 * 4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (6 * 4))) = uint32(uintptr(uintptr(utf847)))

		case ffrwd_av_node_types.ClockSelfClocked:

			*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (5 * 4))) = int8(int32(3))

		default:
			panic("unreachable")
		}
		var result48 int32
		if (payload).Pure {
			result48 = 1
		} else {
			result48 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 * 4))) = int8(result48)
		var result49 int32
		if (payload).OneToOne {
			result49 = 1
		} else {
			result49 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (1 + 8*4))) = int8(result49)
		var result50 int32
		if (payload).Bounded {
			result50 = 1
		} else {
			result50 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 + 8*4))) = int8(result50)
		slice52 := (payload).Relation
		length54 := uint32(len(slice52))
		result53 := witRuntime.Allocate(pinner, uintptr(length54*(2*4)), 4)
		for index, element := range slice52 {
			base := unsafe.Add(result53, index*(2*4))
			utf851 := unsafe.Pointer(unsafe.StringData(element))
			pinner.Pin(utf851)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf851)))

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (10 * 4))) = uint32(length54)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (9 * 4))) = uint32(uintptr(uintptr(result53)))

	case witTypes.ResultErr:
		payload := result1.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf855 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf855)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf855)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_ffrwd:av/node@0.19.0#shape
func wasm_export_post_return_ffrwd_av_node_shape(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport ffrwd:av/node@0.19.0#init
func wasm_export_ffrwd_av_node_init(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 uintptr, arg5 uint32) uintptr {

	pinner := &syncExportPinner
	result42 := make([]ffrwd_av_node_types.BoundStream, 0, arg1)
	for index := 0; index < int(arg1); index++ {
		base := unsafe.Add(unsafe.Pointer(arg0), index*(144+32*4))
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
		value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))))
		value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 5*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 6*4))))
		var option witTypes.Option[float64]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 6*4)))) {
		case 0:

			option = witTypes.None[float64]()
		case 1:

			option = witTypes.Some[float64](*(*float64)(unsafe.Add(unsafe.Pointer(base), (24 + 6*4))))
		default:
			panic("unreachable")
		}
		result := make([]witTypes.Tuple2[string, string], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (32 + 7*4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (32 + 7*4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (32 + 6*4))))), index*(4*4))
			value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
			value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

			result = append(result, witTypes.Tuple2[string, string]{value2, value3})
		}

		var option32 witTypes.Option[ffrwd_av_node_types.OutputFormat]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 8*4)))) {
		case 0:

			option32 = witTypes.None[ffrwd_av_node_types.OutputFormat]()
		case 1:
			var variant31 ffrwd_av_node_types.OutputFormat
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 9*4)))) {
			case 0:
				value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 10*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 11*4))))
				var option9 witTypes.Option[ffrwd_av_types.ColorInfo]
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 12*4)))) {
				case 0:

					option9 = witTypes.None[ffrwd_av_types.ColorInfo]()
				case 1:
					value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 13*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 14*4))))
					value6 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 15*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 16*4))))
					value7 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 17*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 18*4))))
					value8 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 19*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 20*4))))

					option9 = witTypes.Some[ffrwd_av_types.ColorInfo](ffrwd_av_types.ColorInfo{value5, value6, value7, value8})
				default:
					panic("unreachable")
				}

				variant31 = ffrwd_av_node_types.MakeOutputFormatVideo(ffrwd_av_types.VideoFormat{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (40 + 10*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (44 + 10*4)))), value4, option9})

			case 1:
				value10 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 10*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 11*4))))
				var option12 witTypes.Option[string]
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 12*4)))) {
				case 0:

					option12 = witTypes.None[string]()
				case 1:
					value11 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 13*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 14*4))))

					option12 = witTypes.Some[string](value11)
				default:
					panic("unreachable")
				}

				variant31 = ffrwd_av_node_types.MakeOutputFormatAudio(ffrwd_av_types.AudioFormat{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (40 + 10*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (44 + 10*4)))), value10, option12})

			case 2:
				value13 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 10*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 11*4))))

				variant31 = ffrwd_av_node_types.MakeOutputFormatData(value13)

			case 3:
				value14 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 10*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 11*4))))
				var variant ffrwd_av_types.CodedFormat
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 12*4)))) {
				case 0:
					var option15 witTypes.Option[ffrwd_av_types.Rational]
					switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 13*4)))) {
					case 0:

						option15 = witTypes.None[ffrwd_av_types.Rational]()
					case 1:

						option15 = witTypes.Some[ffrwd_av_types.Rational](ffrwd_av_types.Rational{*(*int32)(unsafe.Add(unsafe.Pointer(base), (60 + 13*4))), *(*int32)(unsafe.Add(unsafe.Pointer(base), (64 + 13*4)))})
					default:
						panic("unreachable")
					}
					var option20 witTypes.Option[ffrwd_av_types.ColorInfo]
					switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 14*4)))) {
					case 0:

						option20 = witTypes.None[ffrwd_av_types.ColorInfo]()
					case 1:
						value16 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 15*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 16*4))))
						value17 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 17*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 18*4))))
						value18 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 19*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 20*4))))
						value19 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 21*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 22*4))))

						option20 = witTypes.Some[ffrwd_av_types.ColorInfo](ffrwd_av_types.ColorInfo{value16, value17, value18, value19})
					default:
						panic("unreachable")
					}

					variant = ffrwd_av_types.MakeCodedFormatVideo(ffrwd_av_types.CodedVideo{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (48 + 13*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (52 + 13*4)))), option15, option20})

				case 1:
					var option22 witTypes.Option[string]
					switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 13*4)))) {
					case 0:

						option22 = witTypes.None[string]()
					case 1:
						value21 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 14*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (56 + 15*4))))

						option22 = witTypes.Some[string](value21)
					default:
						panic("unreachable")
					}

					variant = ffrwd_av_types.MakeCodedFormatAudio(ffrwd_av_types.CodedAudio{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (48 + 13*4)))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (52 + 13*4)))), option22})

				case 2:

					variant = ffrwd_av_types.MakeCodedFormatData()

				default:
					panic("unreachable")
				}
				value23 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 23*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 24*4))))
				var option24 witTypes.Option[int32]
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (64 + 25*4)))) {
				case 0:

					option24 = witTypes.None[int32]()
				case 1:

					option24 = witTypes.Some[int32](*(*int32)(unsafe.Add(unsafe.Pointer(base), (68 + 25*4))))
				default:
					panic("unreachable")
				}
				var option25 witTypes.Option[int32]
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (72 + 25*4)))) {
				case 0:

					option25 = witTypes.None[int32]()
				case 1:

					option25 = witTypes.Some[int32](*(*int32)(unsafe.Add(unsafe.Pointer(base), (76 + 25*4))))
				default:
					panic("unreachable")
				}

				variant31 = ffrwd_av_node_types.MakeOutputFormatPackets(ffrwd_av_types.CodedStream{value14, ffrwd_av_types.Rational{*(*int32)(unsafe.Add(unsafe.Pointer(base), (40 + 12*4))), *(*int32)(unsafe.Add(unsafe.Pointer(base), (44 + 12*4)))}, variant, value23, option24, option25})

			case 4:
				value26 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 10*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 11*4))))
				var option28 witTypes.Option[string]
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 12*4)))) {
				case 0:

					option28 = witTypes.None[string]()
				case 1:
					value27 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 13*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 14*4))))

					option28 = witTypes.Some[string](value27)
				default:
					panic("unreachable")
				}
				var option30 witTypes.Option[string]
				switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 15*4)))) {
				case 0:

					option30 = witTypes.None[string]()
				case 1:
					value29 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 16*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 17*4))))

					option30 = witTypes.Some[string](value29)
				default:
					panic("unreachable")
				}

				variant31 = ffrwd_av_node_types.MakeOutputFormatLike(ffrwd_av_node_types.LikeInput{value26, option28, option30})

			default:
				panic("unreachable")
			}

			option32 = witTypes.Some[ffrwd_av_node_types.OutputFormat](variant31)
		default:
			panic("unreachable")
		}
		var option34 witTypes.Option[string]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (88 + 24*4)))) {
		case 0:

			option34 = witTypes.None[string]()
		case 1:
			value33 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (88 + 25*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (88 + 26*4))))

			option34 = witTypes.Some[string](value33)
		default:
			panic("unreachable")
		}
		var option35 witTypes.Option[uint64]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (96 + 26*4)))) {
		case 0:

			option35 = witTypes.None[uint64]()
		case 1:

			option35 = witTypes.Some[uint64](uint64(*(*int64)(unsafe.Add(unsafe.Pointer(base), (104 + 26*4)))))
		default:
			panic("unreachable")
		}
		var option37 witTypes.Option[string]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (112 + 26*4)))) {
		case 0:

			option37 = witTypes.None[string]()
		case 1:
			value36 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (112 + 27*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (112 + 28*4))))

			option37 = witTypes.Some[string](value36)
		default:
			panic("unreachable")
		}
		var option39 witTypes.Option[string]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (112 + 29*4)))) {
		case 0:

			option39 = witTypes.None[string]()
		case 1:
			value38 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (112 + 30*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (112 + 31*4))))

			option39 = witTypes.Some[string](value38)
		default:
			panic("unreachable")
		}
		var option40 witTypes.Option[uint32]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (112 + 32*4)))) {
		case 0:

			option40 = witTypes.None[uint32]()
		case 1:

			option40 = witTypes.Some[uint32](uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (116 + 32*4)))))
		default:
			panic("unreachable")
		}
		var option41 witTypes.Option[float64]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (128 + 32*4)))) {
		case 0:

			option41 = witTypes.None[float64]()
		case 1:

			option41 = witTypes.Some[float64](*(*float64)(unsafe.Add(unsafe.Pointer(base), (136 + 32*4))))
		default:
			panic("unreachable")
		}

		result42 = append(result42, ffrwd_av_node_types.BoundStream{value, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))), ffrwd_av_types.StreamInfo{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4)))), value0, value1, option, result, ffrwd_av_types.Rational{*(*int32)(unsafe.Add(unsafe.Pointer(base), (32 + 8*4))), *(*int32)(unsafe.Add(unsafe.Pointer(base), (36 + 8*4)))}}, option32, ffrwd_av_types.RenditionMeta{option34, option35, option37, option39}, option40, uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), (120 + 32*4)))), option41})
	}

	result44 := make([]string, 0, arg3)
	for index := 0; index < int(arg3); index++ {
		base := unsafe.Add(unsafe.Pointer(arg2), index*(2*4))
		value43 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

		result44 = append(result44, value43)
	}

	value45 := unsafe.String((*uint8)(unsafe.Pointer(arg4)), arg5)
	witRuntime.Unpin()
	result46 := export_ffrwd_av_node.Init(result42, result44, value45)

	switch result46.Tag() {
	case witTypes.ResultOk:

		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case witTypes.ResultErr:
		payload := result46.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_ffrwd:av/node@0.19.0#init
func wasm_export_post_return_ffrwd_av_node_init(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport ffrwd:av/node@0.19.0#set-params
func wasm_export_ffrwd_av_node_set_params(arg0 uintptr, arg1 uint32) uintptr {

	pinner := &syncExportPinner
	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	witRuntime.Unpin()
	result := export_ffrwd_av_node.SetParams(value)

	switch result.Tag() {
	case witTypes.ResultOk:

		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case witTypes.ResultErr:
		payload := result.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_ffrwd:av/node@0.19.0#set-params
func wasm_export_post_return_ffrwd_av_node_set_params(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport ffrwd:av/node@0.19.0#process
func wasm_export_ffrwd_av_node_process(arg0 int32) uintptr {

	pinner := &syncExportPinner
	result := export_ffrwd_av_node.Process(ffrwd_av_node_tick.TickFromBorrowHandle(int32(uintptr(arg0))))

	switch result.Tag() {
	case witTypes.ResultOk:
		payload := result.Ok()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))
		slice := (payload).Items
		length := uint32(len(slice))
		result3 := witRuntime.Allocate(pinner, uintptr(length*(56+4*4)), 8)
		for index, element := range slice {
			base := unsafe.Add(result3, index*(56+4*4))
			utf8 := unsafe.Pointer(unsafe.StringData((element).Port))
			pinner.Pin(utf8)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len((element).Port)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))

			switch (element).Payload.Tag() {
			case ffrwd_av_node.PayloadFrame:
				payload := (element).Payload.Frame()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = int8(int32(0))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = (payload).Pts

				switch (payload).Duration.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Duration.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4))) = int8(int32(1))
					*(*int64)(unsafe.Add(unsafe.Pointer(base), (24 + 2*4))) = payload

				default:
					panic("unreachable")
				}
				data := unsafe.Pointer(unsafe.SliceData((payload).Data))
				pinner.Pin(data)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (32 + 3*4))) = uint32(uint32(len((payload).Data)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (32 + 2*4))) = uint32(uintptr(uintptr(data)))

			case ffrwd_av_node.PayloadSame:
				payload := (element).Payload.Same()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = int8(int32(1))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = (payload).Pts

				switch (payload).Duration.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Duration.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4))) = int8(int32(1))
					*(*int64)(unsafe.Add(unsafe.Pointer(base), (24 + 2*4))) = payload

				default:
					panic("unreachable")
				}
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (32 + 2*4))) = int32((payload).Id)
				*(*int32)(unsafe.Add(unsafe.Pointer(base), (36 + 2*4))) = int32((payload).Index)

			case ffrwd_av_node.PayloadMessage:
				payload := (element).Payload.Message()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = int8(int32(2))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = (payload).Pts
				data0 := unsafe.Pointer(unsafe.SliceData((payload).Data))
				pinner.Pin(data0)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 3*4))) = uint32(uint32(len((payload).Data)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4))) = uint32(uintptr(uintptr(data0)))

			case ffrwd_av_node.PayloadPacket:
				payload := (element).Payload.Packet()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = int8(int32(3))
				*(*int64)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = (payload).Pts

				switch (payload).Dts.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Dts.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4))) = int8(int32(1))
					*(*int64)(unsafe.Add(unsafe.Pointer(base), (24 + 2*4))) = payload

				default:
					panic("unreachable")
				}

				switch (payload).Duration.Tag() {
				case witTypes.OptionNone:
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (32 + 2*4))) = int8(int32(0))

				case witTypes.OptionSome:
					payload := (payload).Duration.Some()
					*(*int8)(unsafe.Add(unsafe.Pointer(base), (32 + 2*4))) = int8(int32(1))
					*(*int64)(unsafe.Add(unsafe.Pointer(base), (40 + 2*4))) = payload

				default:
					panic("unreachable")
				}
				var result1 int32
				if (payload).Keyframe {
					result1 = 1
				} else {
					result1 = 0
				}
				*(*int8)(unsafe.Add(unsafe.Pointer(base), (48 + 2*4))) = int8(result1)
				data2 := unsafe.Pointer(unsafe.SliceData((payload).Data))
				pinner.Pin(data2)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 4*4))) = uint32(uint32(len((payload).Data)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (48 + 3*4))) = uint32(uintptr(uintptr(data2)))

			default:
				panic("unreachable")
			}

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(length)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(result3)))
		slice5 := (payload).Rows
		length7 := uint32(len(slice5))
		result6 := witRuntime.Allocate(pinner, uintptr(length7*(2*4)), 4)
		for index, element := range slice5 {
			base := unsafe.Add(result6, index*(2*4))
			utf84 := unsafe.Pointer(unsafe.StringData(element))
			pinner.Pin(utf84)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf84)))

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (4 * 4))) = uint32(length7)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (3 * 4))) = uint32(uintptr(uintptr(result6)))
		var result8 int32
		if (payload).Finished {
			result8 = 1
		} else {
			result8 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (5 * 4))) = int8(result8)

	case witTypes.ResultErr:
		payload := result.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf89 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf89)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf89)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_ffrwd:av/node@0.19.0#process
func wasm_export_post_return_ffrwd_av_node_process(result uintptr) {
	syncExportPinner.Unpin()
}

// Unused, but present to make the compiler happy
func main() {}
