// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     ffrwd:av@0.10.0
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:random@0.2.0
//     wasi:cli@0.2.0
//     ffrwd:av-go@0.1.0

package wasi_cli_terminal_input

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
)

//go:wasmimport wasi:cli/terminal-input@0.2.0 [resource-drop]terminal-input
func resourceDropTerminalInput(handle int32)

// The input side of a terminal.
type TerminalInput struct {
	handle *witRuntime.Handle
}

func (self *TerminalInput) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *TerminalInput) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *TerminalInput) Handle() int32 {
	return self.handle.Use()
}

func (self *TerminalInput) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropTerminalInput(handle)
	}
}

func TerminalInputFromOwnHandle(handleValue int32) *TerminalInput {
	handle := witRuntime.MakeHandle(handleValue)
	value := &TerminalInput{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropTerminalInput(handleValue)
		}
	}, 0)
	return value
}

func TerminalInputFromBorrowHandle(handleValue int32) *TerminalInput {
	handle := witRuntime.MakeHandle(handleValue)
	return &TerminalInput{handle}
}
