// Code generated by wit-bindgen-go. DO NOT EDIT.

package node

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// PacketShape is used for storage in variant or result types.
type PacketShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Packet{})]byte
}

// NodeShapeShape is used for storage in variant or result types.
type NodeShapeShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(NodeShape{})]byte
}

// EmittedShape is used for storage in variant or result types.
type EmittedShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Emitted{})]byte
}
