// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package node represents the exported interface "ffrwd:av/node@0.19.1".
//
// A node: typed inputs, typed outputs and a clock, its shape from its
// params.
package node

import (
	nodetick "github.com/imbcmdth/ffrwd/sidecar/modules-go/internal/ffrwd/av/node-tick"
	nodetypes "github.com/imbcmdth/ffrwd/sidecar/modules-go/internal/ffrwd/av/node-types"
	"github.com/imbcmdth/ffrwd/sidecar/modules-go/internal/ffrwd/av/types"
	"go.bytecodealliance.org/cm"
)

// Meta represents the type alias "ffrwd:av/node@0.19.1#meta".
//
// See [types.Meta] for more information.
type Meta = types.Meta

// Packet represents the type alias "ffrwd:av/node@0.19.1#packet".
//
// See [types.Packet] for more information.
type Packet = types.Packet

// RawFrame represents the type alias "ffrwd:av/node@0.19.1#raw-frame".
//
// See [types.RawFrame] for more information.
type RawFrame = types.RawFrame

// Binding represents the type alias "ffrwd:av/node@0.19.1#binding".
//
// See [nodetypes.Binding] for more information.
type Binding = nodetypes.Binding

// BoundStream represents the type alias "ffrwd:av/node@0.19.1#bound-stream".
//
// See [nodetypes.BoundStream] for more information.
type BoundStream = nodetypes.BoundStream

// Message represents the type alias "ffrwd:av/node@0.19.1#message".
//
// See [nodetypes.Message] for more information.
type Message = nodetypes.Message

// NodeShape represents the type alias "ffrwd:av/node@0.19.1#node-shape".
//
// See [nodetypes.NodeShape] for more information.
type NodeShape = nodetypes.NodeShape

// Tick represents the exported type alias "ffrwd:av/node@0.19.1#tick".
//
// See [nodetick.Tick] for more information.
type Tick = nodetick.Tick

// SameFrame represents the record "ffrwd:av/node@0.19.1#same-frame".
//
// An input frame's bytes leaving on an output, never copied into the
// module: frame `index` of stream `id`'s `frames` this tick. Its format
// must be the port's (size and pixel format, or sample format, rate and
// channels); the host ends the run otherwise. Audio may leave this way
// only from an input whose stride is its window, since overlapping
// windows would emit samples twice.
//
//	record same-frame {
//		pts: s64,
//		duration: option<s64>,
//		id: u32,
//		index: u32,
//	}
type SameFrame struct {
	_        cm.HostLayout    `json:"-"`
	Pts      int64            `json:"pts"`
	Duration cm.Option[int64] `json:"duration"`
	ID       uint32           `json:"id"`
	Index    uint32           `json:"index"`
}

// Payload represents the variant "ffrwd:av/node@0.19.1#payload".
//
// One thing leaving. Its pts and duration are in its port's time base,
// and the module's to choose.
//
//	variant payload {
//		frame(raw-frame),
//		same(same-frame),
//		message(message),
//		packet(packet),
//	}
type Payload cm.Variant[uint8, PacketShape, Packet]

// PayloadFrame returns a [Payload] of case "frame".
//
// New bytes in the port's format: one frame's pixels, tightly packed,
// or a run of interleaved samples.
func PayloadFrame(data RawFrame) Payload {
	return cm.New[Payload](0, data)
}

// Frame returns a non-nil *[RawFrame] if [Payload] represents the variant case "frame".
func (self *Payload) Frame() *RawFrame {
	return cm.Case[RawFrame](self, 0)
}

// PayloadSame returns a [Payload] of case "same".
func PayloadSame(data SameFrame) Payload {
	return cm.New[Payload](1, data)
}

// Same returns a non-nil *[SameFrame] if [Payload] represents the variant case "same".
func (self *Payload) Same() *SameFrame {
	return cm.Case[SameFrame](self, 1)
}

// PayloadMessage returns a [Payload] of case "message".
//
// For codec "json", one UTF-8 JSON object. Empty: a progress mark,
// never delivered; the port's progress stands at its pts.
func PayloadMessage(data Message) Payload {
	return cm.New[Payload](2, data)
}

// Message returns a non-nil *[Message] if [Payload] represents the variant case "message".
func (self *Payload) Message() *Message {
	return cm.Case[Message](self, 2)
}

// PayloadPacket returns a [Payload] of case "packet".
func PayloadPacket(data Packet) Payload {
	return cm.New[Payload](3, data)
}

// Packet returns a non-nil *[Packet] if [Payload] represents the variant case "packet".
func (self *Payload) Packet() *Packet {
	return cm.Case[Packet](self, 3)
}

var _PayloadStrings = [4]string{
	"frame",
	"same",
	"message",
	"packet",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Payload) String() string {
	return _PayloadStrings[v.Tag()]
}

// Emission represents the record "ffrwd:av/node@0.19.1#emission".
//
//	record emission {
//		port: string,
//		payload: payload,
//	}
type Emission struct {
	_ cm.HostLayout `json:"-"`
	// An output's name in the node's shape.
	Port    string  `json:"port"`
	Payload Payload `json:"payload"`
}

// Emitted represents the record "ffrwd:av/node@0.19.1#emitted".
//
// What one tick produced.
//
//	record emitted {
//		items: list<emission>,
//		rows: list<string>,
//		finished: bool,
//	}
type Emitted struct {
	_ cm.HostLayout `json:"-"`
	// Per port, frames and messages never go back in pts, within a call
	// or across calls, and packets keep decode order with dts never
	// decreasing. Ports interleave freely.
	Items cm.List[Emission] `json:"items"`

	// Rows for the run's rows output, as a sink's are.
	Rows cm.List[string] `json:"rows"`

	// Nothing more will leave: the host makes the last call and then ends
	// every output. A node on an input clock ends with that input and need
	// not set it.
	Finished bool `json:"finished"`
}
