// Code generated by wit-bindgen-go. DO NOT EDIT.

package node

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "ffrwd:av/node@0.19.0".
var Exports struct {
	// Describe represents the caller-defined, exported function "describe".
	//
	// Takes no params, so the compiler validates params before it asks for
	// a shape. A node leaves the format lists empty, since its ports say
	// what they accept in `shape`; `rows-schema` describes `emitted.rows`,
	// each data port carries its own `schema`, and `rows-language` tags
	// every "json" output.
	//
	//	describe: func() -> meta
	Describe func() (result Meta)

	// Shape represents the caller-defined, exported function "shape".
	//
	// The ports and clock for these params, and for `bound`: the inputs
	// the call binds, by the declaration's names, so a shape may turn on
	// what is given (a page with no picture ticks at a rate; an output
	// `like` an unbound input is left out). Called at compile time with the
	// call's static params, once per distinct (module, params, bound), and
	// cached; a source may read the network here to learn its outputs, as
	// `probe` did. Callable at any point in an instance's life: it reads
	// nothing `init` or `set-params` set.
	//
	// The host refuses a shape in which `clock` names no input, or one that
	// is optional, `many` or not lockstep; an input is lockstep with no
	// input clock, or paired other than `arrival` on a self-clocked node;
	// `hold` is on a message kind or `interval` on a frame kind; a data
	// input's `rows` is `ignore`; `like` names an input that is not single
	// and bound; or a stride is 0 or above its window.
	//
	//	shape: func(params: string, bound: list<string>) -> result<node-shape, string>
	Shape func(params string, bound cm.List[string]) (result cm.Result[NodeShapeShape, NodeShape, string])

	// Init represents the caller-defined, exported function "init".
	//
	// Opens an instance for `shape(params, bound)` on the streams bound to
	// its inputs, one entry each: ports in the shape's order, a port's
	// streams in the order the query named them, none for an optional port
	// with nothing bound. Each `id` is distinct and names its stream, in
	// every tick call and in `same`, for the instance's life. `latched`
	// names the outputs the query latched onto; the node may leave the rest
	// unmade.
	//
	//	init: func(bound: list<bound-stream>, latched: list<string>, params: string) ->
	//	result<_, string>
	Init func(bound cm.List[BoundStream], latched cm.List[string], params string) (result cm.Result[string, struct{}, string])

	// SetParams represents the caller-defined, exported function "set-params".
	//
	// Replaces the params between ticks. Params whose shape differs from
	// the instance's are refused by the host and never reach this call, so
	// a pairing's fields and a port's latency never change under an
	// instance; an Err leaves the previous params in force.
	//
	//	set-params: func(params: string) -> result<_, string>
	SetParams func(params string) (result cm.Result[string, struct{}, string])

	// Process represents the caller-defined, exported function "process".
	//
	// One tick. An Err ends the run with its message, as a panic does; a
	// tick with nothing to emit returns Ok with nothing. A self-clocked
	// node's call may wait until it has something, and is called again as
	// soon as it returns.
	//
	// Unless the node is self-clocked, returning promises that no output
	// still has anything to send stamped earlier than the end of the tick's
	// interval less the port's `latency`. The host sends that time down
	// each data edge as the node's progress, and never less than the last
	// message's pts; a message that breaks the promise reaches its
	// consumers late, and is reported.
	//
	//	process: func(tick: borrow<tick>) -> result<emitted, string>
	Process func(tick cm.Rep) (result cm.Result[EmittedShape, Emitted, string])
}
