// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     ffrwd:av@0.10.0
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:random@0.2.0
//     wasi:cli@0.2.0
//     ffrwd:av-go@0.1.0

package wasi_sockets_instance_network

import (
	"wit_component/wasi_sockets_network"
)

type Network = wasi_sockets_network.Network

//go:wasmimport wasi:sockets/instance-network@0.2.0 instance-network
func wasm_import_instance_network() int32

func InstanceNetwork() *wasi_sockets_network.Network {

	result := wasm_import_instance_network()
	return wasi_sockets_network.NetworkFromOwnHandle(int32(uintptr(result)))

}
