// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     ffrwd:av@0.10.0
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:random@0.2.0
//     wasi:cli@0.2.0
//     ffrwd:av-go@0.1.0

package wasi_cli_terminal_stdin

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/wasi_cli_terminal_input"
)

type TerminalInput = wasi_cli_terminal_input.TerminalInput

//go:wasmimport wasi:cli/terminal-stdin@0.2.0 get-terminal-stdin
func wasm_import_get_terminal_stdin(arg0 uintptr)

func GetTerminalStdin() witTypes.Option[*wasi_cli_terminal_input.TerminalInput] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	wasm_import_get_terminal_stdin(returnArea)
	var option witTypes.Option[*wasi_cli_terminal_input.TerminalInput]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[*wasi_cli_terminal_input.TerminalInput]()
	case 1:

		option = witTypes.Some[*wasi_cli_terminal_input.TerminalInput](wasi_cli_terminal_input.TerminalInputFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	default:
		panic("unreachable")
	}
	result := option
	return result

}
