// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     ffrwd:av@0.10.0
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:random@0.2.0
//     wasi:cli@0.2.0
//     ffrwd:av-go@0.1.0

package ffrwd_av_window_filter

import (
	"wit_component/ffrwd_av_types"
)

type Format = ffrwd_av_types.Format
type Meta = ffrwd_av_types.Meta
type StreamInfo = ffrwd_av_types.StreamInfo

// One input payload: its timestamp, its bytes, and the rows that arrived
// with it - each an NDJSON line an upstream module produced, empty when
// nothing came with it.
//
// For a video instance the bytes are one frame's pixels. For an audio
// instance they are interleaved samples in the instance's sample format,
// the whole window in one contiguous piece: the host re-cuts whatever
// packets arrived, so a module never sees a packet boundary. `pts` is the
// first sample's tick.
//
// Rows ride pad 0. A module reading several streams is handed whatever
// arrived on pad 0 here, and the rows that arrived on any other pad are
// dropped before the call - so `rows` is empty on every pad past the
// first.
type InFrame struct {
	Pts   int64
	Frame []uint8
	Rows  []string
}

const (
	// New bytes: one frame's pixels, or interleaved samples.
	FramePayloadNew uint8 = 0
	// An input's bytes, which the module never copied out: the input this
	// call received at the same pts, or - when the call received exactly one
	// input - that one, whatever pts the output carries. For a module
	// reading several streams this is pad 0's bytes, since every pad shares
	// the call's one pts. An audio module may say this only when its stride
	// is its window, since overlapping windows passed through would emit
	// every sample more than once.
	FramePayloadSame uint8 = 1
)

// Where an output payload's bytes come from.
type FramePayload struct {
	tag   uint8
	value any
}

func (self FramePayload) Tag() uint8 {
	return self.tag
}

func (self FramePayload) New() []uint8 {
	if self.tag != FramePayloadNew {
		panic("tag mismatch")
	}
	return self.value.([]uint8)
}

func MakeFramePayloadNew(value []uint8) FramePayload {
	return FramePayload{FramePayloadNew, value}
}
func MakeFramePayloadSame() FramePayload {
	return FramePayload{FramePayloadSame, nil}
}

// One output. Its pts is the module's to choose: a module may move its
// payload in time, drop it, or emit several from one.
type OutFrame struct {
	Pts   int64
	Frame FramePayload
	Rows  []string
}

// `meta`, plus how the host must drive this module.
type WindowMeta struct {
	Meta ffrwd_av_types.Meta
	// What one `process` call receives: frames for a video module, SAMPLES
	// for an audio one. 1 is plain streaming for video; an audio module
	// names a chunk it is happy to work in, and the host cuts that chunk out
	// of whatever packets arrive.
	Window uint32
	// How much is consumed per call, never more than `window`, in the same
	// unit. `window` makes the windows disjoint.
	Stride uint32
	// Whether a call depends only on what it was handed. False makes
	// parallel hosting unsound and a host must refuse it.
	Pure bool
	// For video: whether every call returns exactly one output per frame it
	// consumed, each at that frame's own pts. For audio: whether the samples
	// leaving over the instance's life are the samples that arrived, neither
	// dropped nor invented - per-call counts may differ, but the output runs
	// on without gap or overlap. Neither window nor stride settles this, so
	// it is declared.
	OneToOne bool
	// Whether this module ACTS on the rows arriving with its payloads. Every
	// call receives them whatever this says, so availability is no answer: a
	// module that only carries rows through declares false, and one that
	// reads what an upstream module detected declares true.
	ReadsRows bool
	// Whether upstream rows may appear on this module's own output. False
	// means the rows leaving are the module's own, or none. It speaks of pad
	// 0: rows arrive there and nowhere else.
	ForwardsRows bool
	// How many streams this module reads. Frames arrive one per pad, in pad
	// order, all at the same pts. 1 is the ordinary module, reading one
	// stream. More than 1 is window 1, stride 1 - a call takes one frame off
	// each pad and hands one back - and a host refuses any other shape.
	Inputs uint32
}

// What one call produced.
type Processed struct {
	Frames []OutFrame
	// Rows with nothing to ride. Only the last call may fill this.
	Trailing []string
}
