// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package nodemodulego represents the world "ffrwd:av-go/node-module-go@0.2.0".
//
// What a TinyGo module targets. It imports and exports what `ffrwd:av`'s own
// `node-module` does, and means exactly that; the wasi imports are the
// difference. TinyGo's runtime reaches for the environment, the clock and
// stdio whatever the module itself does, and a world declaring no imports
// cannot be encoded around a core module that has them.
package nodemodulego
