// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     ffrwd:av@0.10.0
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:random@0.2.0
//     wasi:cli@0.2.0
//     ffrwd:av-go@0.1.0

package wasi_sockets_tcp_create_socket

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/wasi_sockets_network"
	"wit_component/wasi_sockets_tcp"
)

type Network = wasi_sockets_network.Network
type ErrorCode = wasi_sockets_network.ErrorCode
type IpAddressFamily = wasi_sockets_network.IpAddressFamily
type TcpSocket = wasi_sockets_tcp.TcpSocket

//go:wasmimport wasi:sockets/tcp-create-socket@0.2.0 create-tcp-socket
func wasm_import_create_tcp_socket(arg0 int32, arg1 uintptr)

func CreateTcpSocket(addressFamily wasi_sockets_network.IpAddressFamily) witTypes.Result[*wasi_sockets_tcp.TcpSocket, wasi_sockets_network.ErrorCode] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	wasm_import_create_tcp_socket(int32(addressFamily), returnArea)
	var result witTypes.Result[*wasi_sockets_tcp.TcpSocket, wasi_sockets_network.ErrorCode]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result = witTypes.Ok[*wasi_sockets_tcp.TcpSocket, wasi_sockets_network.ErrorCode](wasi_sockets_tcp.TcpSocketFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:

		result = witTypes.Err[*wasi_sockets_tcp.TcpSocket, wasi_sockets_network.ErrorCode](uint8(uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))))
	default:
		panic("unreachable")
	}
	result0 := result
	return result0

}
