// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     ffrwd:av@0.10.0
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:random@0.2.0
//     wasi:cli@0.2.0
//     ffrwd:av-go@0.1.0

package main

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/export_ffrwd_av_window_filter"
	"wit_component/ffrwd_av_types"
	"wit_component/ffrwd_av_window_filter"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, (16 + 18*4), 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport ffrwd:av/window-filter@0.10.0#describe
func wasm_export_ffrwd_av_window_filter_describe() uintptr {

	pinner := &syncExportPinner
	result := export_ffrwd_av_window_filter.Describe()
	utf8 := unsafe.Pointer(unsafe.StringData(((result).Meta).Name))
	pinner.Pin(utf8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uint32(len(((result).Meta).Name)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(utf8)))
	utf80 := unsafe.Pointer(unsafe.StringData(((result).Meta).Version))
	pinner.Pin(utf80)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (3 * 4))) = uint32(uint32(len(((result).Meta).Version)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uintptr(uintptr(utf80)))
	utf81 := unsafe.Pointer(unsafe.StringData(((result).Meta).ParamsSchema))
	pinner.Pin(utf81)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (5 * 4))) = uint32(uint32(len(((result).Meta).ParamsSchema)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (4 * 4))) = uint32(uintptr(uintptr(utf81)))
	utf82 := unsafe.Pointer(unsafe.StringData(((result).Meta).RowsSchema))
	pinner.Pin(utf82)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (7 * 4))) = uint32(uint32(len(((result).Meta).RowsSchema)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (6 * 4))) = uint32(uintptr(uintptr(utf82)))
	slice := ((result).Meta).PixelFormats
	length := uint32(len(slice))
	result4 := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result4, index*(2*4))
		utf83 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf83)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf83)))

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (9 * 4))) = uint32(length)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 * 4))) = uint32(uintptr(uintptr(result4)))
	slice6 := ((result).Meta).SampleFormats
	length8 := uint32(len(slice6))
	result7 := witRuntime.Allocate(pinner, uintptr(length8*(2*4)), 4)
	for index, element := range slice6 {
		base := unsafe.Add(result7, index*(2*4))
		utf85 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf85)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf85)))

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (11 * 4))) = uint32(length8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (10 * 4))) = uint32(uintptr(uintptr(result7)))
	data := unsafe.Pointer(unsafe.SliceData(((result).Meta).SampleRates))
	pinner.Pin(data)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (13 * 4))) = uint32(uint32(len(((result).Meta).SampleRates)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (12 * 4))) = uint32(uintptr(uintptr(data)))
	data9 := unsafe.Pointer(unsafe.SliceData(((result).Meta).ChannelCounts))
	pinner.Pin(data9)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (15 * 4))) = uint32(uint32(len(((result).Meta).ChannelCounts)))
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (14 * 4))) = uint32(uintptr(uintptr(data9)))
	slice11 := ((result).Meta).RowsLanguage
	length13 := uint32(len(slice11))
	result12 := witRuntime.Allocate(pinner, uintptr(length13*(2*4)), 4)
	for index, element := range slice11 {
		base := unsafe.Add(result12, index*(2*4))
		utf810 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf810)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf810)))

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (17 * 4))) = uint32(length13)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (16 * 4))) = uint32(uintptr(uintptr(result12)))
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (18 * 4))) = int32((result).Window)
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (4 + 18*4))) = int32((result).Stride)
	var result14 int32
	if (result).Pure {
		result14 = 1
	} else {
		result14 = 0
	}
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (8 + 18*4))) = int8(result14)
	var result15 int32
	if (result).OneToOne {
		result15 = 1
	} else {
		result15 = 0
	}
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (9 + 18*4))) = int8(result15)
	var result16 int32
	if (result).ReadsRows {
		result16 = 1
	} else {
		result16 = 0
	}
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (10 + 18*4))) = int8(result16)
	var result17 int32
	if (result).ForwardsRows {
		result17 = 1
	} else {
		result17 = 0
	}
	*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), (11 + 18*4))) = int8(result17)
	*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (12 + 18*4))) = int32((result).Inputs)
	return exportReturnArea

}

//go:wasmexport cabi_post_ffrwd:av/window-filter@0.10.0#describe
func wasm_export_post_return_ffrwd_av_window_filter_describe(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport ffrwd:av/window-filter@0.10.0#init
func wasm_export_ffrwd_av_window_filter_init(arg0 uintptr) uintptr {

	pinner := &syncExportPinner
	var variant ffrwd_av_types.Format
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), 0))) {
	case 0:
		value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (8 + 2*4))))

		variant = ffrwd_av_types.MakeFormatVideo(ffrwd_av_types.VideoFormat{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 4))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), (4 + 1*4)))), value})

	case 1:
		value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (8 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (8 + 2*4))))

		variant = ffrwd_av_types.MakeFormatAudio(ffrwd_av_types.AudioFormat{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), 4))), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), (4 + 1*4)))), value0})

	default:
		panic("unreachable")
	}
	value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 3*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 4*4))))
	value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 5*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 6*4))))
	var option witTypes.Option[float64]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (24 + 6*4)))) {
	case 0:

		option = witTypes.None[float64]()
	case 1:

		option = witTypes.Some[float64](*(*float64)(unsafe.Add(unsafe.Pointer(arg0), (32 + 6*4))))
	default:
		panic("unreachable")
	}
	result := make([]witTypes.Tuple2[string, string], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (40 + 7*4))))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (40 + 7*4)))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (40 + 6*4))))), index*(4*4))
		value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
		value4 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

		result = append(result, witTypes.Tuple2[string, string]{value3, value4})
	}

	value5 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (48 + 8*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(arg0), (48 + 9*4))))
	witRuntime.Unpin()
	result6 := export_ffrwd_av_window_filter.Init(variant, ffrwd_av_types.StreamInfo{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(arg0), (16 + 2*4)))), value1, value2, option, result, ffrwd_av_types.Rational{*(*int32)(unsafe.Add(unsafe.Pointer(arg0), (40 + 8*4))), *(*int32)(unsafe.Add(unsafe.Pointer(arg0), (44 + 8*4)))}}, value5)

	switch result6.Tag() {
	case witTypes.ResultOk:

		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case witTypes.ResultErr:
		payload := result6.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_ffrwd:av/window-filter@0.10.0#init
func wasm_export_post_return_ffrwd_av_window_filter_init(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport ffrwd:av/window-filter@0.10.0#set-params
func wasm_export_ffrwd_av_window_filter_set_params(arg0 uintptr, arg1 uint32) uintptr {

	pinner := &syncExportPinner
	value := unsafe.String((*uint8)(unsafe.Pointer(arg0)), arg1)
	witRuntime.Unpin()
	result := export_ffrwd_av_window_filter.SetParams(value)

	switch result.Tag() {
	case witTypes.ResultOk:

		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case witTypes.ResultErr:
		payload := result.Err()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		utf8 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uint32(len(payload)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(utf8)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_ffrwd:av/window-filter@0.10.0#set-params
func wasm_export_post_return_ffrwd_av_window_filter_set_params(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport ffrwd:av/window-filter@0.10.0#process
func wasm_export_ffrwd_av_window_filter_process(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32, arg4 int32) uintptr {

	pinner := &syncExportPinner
	result1 := make([]ffrwd_av_window_filter.InFrame, 0, arg1)
	for index := 0; index < int(arg1); index++ {
		base := unsafe.Add(unsafe.Pointer(arg0), index*(8+4*4))
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))
		result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))))), index*(2*4))
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value0)
		}

		result1 = append(result1, ffrwd_av_window_filter.InFrame{*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)), value, result})
	}

	result3 := make([]string, 0, arg3)
	for index := 0; index < int(arg3); index++ {
		base := unsafe.Add(unsafe.Pointer(arg2), index*(2*4))
		value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

		result3 = append(result3, value2)
	}

	witRuntime.Unpin()
	result4 := export_ffrwd_av_window_filter.Process(result1, result3, (arg4 != 0))
	slice6 := (result4).Frames
	length8 := uint32(len(slice6))
	result7 := witRuntime.Allocate(pinner, uintptr(length8*(16+4*4)), 8)
	for index, element := range slice6 {
		base := unsafe.Add(result7, index*(16+4*4))
		*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)) = (element).Pts

		switch (element).Frame.Tag() {
		case ffrwd_av_window_filter.FramePayloadNew:
			payload := (element).Frame.New()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(0))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uintptr(uintptr(data)))

		case ffrwd_av_window_filter.FramePayloadSame:

			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(int32(1))

		default:
			panic("unreachable")
		}
		slice := (element).Rows
		length := uint32(len(slice))
		result5 := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
		for index, element := range slice {
			base := unsafe.Add(result5, index*(2*4))
			utf8 := unsafe.Pointer(unsafe.StringData(element))
			pinner.Pin(utf8)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 4*4))) = uint32(length)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 3*4))) = uint32(uintptr(uintptr(result5)))

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(length8)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(result7)))
	slice10 := (result4).Trailing
	length12 := uint32(len(slice10))
	result11 := witRuntime.Allocate(pinner, uintptr(length12*(2*4)), 4)
	for index, element := range slice10 {
		base := unsafe.Add(result11, index*(2*4))
		utf89 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf89)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf89)))

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (3 * 4))) = uint32(length12)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(uintptr(uintptr(result11)))
	return exportReturnArea

}

//go:wasmexport cabi_post_ffrwd:av/window-filter@0.10.0#process
func wasm_export_post_return_ffrwd_av_window_filter_process(result uintptr) {
	syncExportPinner.Unpin()
}

// Unused, but present to make the compiler happy
func main() {}
