// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     ffrwd:av@0.10.0
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:random@0.2.0
//     wasi:cli@0.2.0
//     ffrwd:av-go@0.1.0

package ffrwd_av_types

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

// Static description of a module, available without running anything.
type Meta struct {
	Name    string
	Version string
	// JSON Schema for the `params` string.
	ParamsSchema string
	// JSON Schema for one row object; empty when the module emits none.
	RowsSchema string
	// Pixel formats accepted, most preferred first. Empty means this is not
	// a video module.
	PixelFormats []string
	// Sample formats accepted, most preferred first: "f32" or "s16", always
	// interleaved. Empty means this is not an audio module. A module is one
	// kind or the other, so exactly one of this and `pixel-formats` is
	// filled in.
	SampleFormats []string
	// Sample rates accepted. Empty is every rate.
	SampleRates []uint32
	// Channel counts accepted. Empty is every count.
	ChannelCounts []uint32
	// Ordered param names; the module's rows' language is the first of these
	// params that is set at the call; empty list = none declared.
	RowsLanguage []string
}

// A ratio of two whole numbers.
type Rational struct {
	Num int32
	Den int32
}

// The frames of a video instance, fixed for the life of the instance.
type VideoFormat struct {
	Width  uint32
	Height uint32
	PixFmt string
}

// The samples of an audio instance, fixed for the life of the instance.
type AudioFormat struct {
	SampleRate uint32
	Channels   uint32
	// "f32" or "s16", interleaved.
	SampleFmt string
}

const (
	FormatVideo uint8 = 0
	FormatAudio uint8 = 1
)

// What an instance is opened for, which is what tells its kind. A module
// is handed the arm its own declaration asked for; the host refuses the
// other one before `init`.
type Format struct {
	tag   uint8
	value any
}

func (self Format) Tag() uint8 {
	return self.tag
}

func (self Format) Video() VideoFormat {
	if self.tag != FormatVideo {
		panic("tag mismatch")
	}
	return self.value.(VideoFormat)
}
func (self Format) Audio() AudioFormat {
	if self.tag != FormatAudio {
		panic("tag mismatch")
	}
	return self.value.(AudioFormat)
}

func MakeFormatVideo(value VideoFormat) Format {
	return Format{FormatVideo, value}
}
func MakeFormatAudio(value AudioFormat) Format {
	return Format{FormatAudio, value}
}

// The stream an instance is attached to, told once at init.
type StreamInfo struct {
	Index uint32
	Kind  string
	Codec string
	// Seconds; absent when unknown.
	Duration witTypes.Option[float64]
	// The stream's own tags.
	Tags []witTypes.Tuple2[string, string]
	// The unit timestamps are counted in, as a fraction of a second. The host
	// always supplies it; `den` is always positive. A windowed module is
	// handed timestamps rather than seconds, so this is how one whose
	// parameters are in seconds converts them. For audio it is what turns a
	// sample position into a timestamp: at 1/48000 one tick is one sample.
	TimeBase Rational
}
