// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package nodetick represents the imported interface "ffrwd:av/node-tick@0.19.0".
//
// What one tick holds.
package nodetick

import (
	nodetypes "github.com/imbcmdth/ffrwd/sidecar/modules-go/internal/ffrwd/av/node-types"
	"github.com/imbcmdth/ffrwd/sidecar/modules-go/internal/ffrwd/av/types"
	"go.bytecodealliance.org/cm"
)

// Rational represents the type alias "ffrwd:av/node-tick@0.19.0#rational".
//
// See [types.Rational] for more information.
type Rational = types.Rational

// Packet represents the type alias "ffrwd:av/node-tick@0.19.0#packet".
//
// See [types.Packet] for more information.
type Packet = types.Packet

// StreamInfo represents the type alias "ffrwd:av/node-tick@0.19.0#stream-info".
//
// See [types.StreamInfo] for more information.
type StreamInfo = types.StreamInfo

// Frame represents the type alias "ffrwd:av/node-tick@0.19.0#frame".
//
// See [nodetypes.Frame] for more information.
type Frame = nodetypes.Frame

// Message represents the type alias "ffrwd:av/node-tick@0.19.0#message".
//
// See [nodetypes.Message] for more information.
type Message = nodetypes.Message

// Feed represents the type alias "ffrwd:av/node-tick@0.19.0#feed".
//
// See [nodetypes.Feed] for more information.
type Feed = nodetypes.Feed

// TimedRows represents the type alias "ffrwd:av/node-tick@0.19.0#timed-rows".
//
// See [nodetypes.TimedRows] for more information.
type TimedRows = nodetypes.TimedRows

// Tick represents the imported resource "ffrwd:av/node-tick@0.19.0#tick".
//
// One call's inputs, held by the host for exactly that call. A stream
// is named by the `id` `init` gave it; an id `init` did not give, or an
// index at or past the length of that stream's `frames`, is a
// fault that stops the run.
//
// The tick's interval runs from its time to the next tick's: one stride
// of a frame clock, one packet of a packets clock, every message
// sharing one pts of a data clock, one period of a rate clock. A last
// call's runs to the end of its inputs. Every input that is not the
// clock hands what falls in it.
//
// The handle is the call's alone: it cannot be kept past the return,
// and bytes a module means to keep are its own copy the moment `fetch`
// hands them over.
//
//	resource tick
type Tick cm.Resource

// ResourceDrop represents the imported resource-drop for resource "tick".
//
// Drops a resource handle.
//
//go:nosplit
func (self Tick) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_TickResourceDrop((uint32)(self0))
	return
}

// EarlierRows represents the imported method "earlier-rows".
//
// For an input whose `rows` is `state`: the rows of every tick this
// instance did not process since its previous call, oldest first,
// each beside the pts it arrived at, all earlier than this call's. An
// instance's first call is handed every one before it. A data input's
// rows are its messages. Empty on every other input.
//
//	earlier-rows: func(id: u32) -> list<timed-rows>
//
//go:nosplit
func (self Tick) EarlierRows(id uint32) (result cm.List[TimedRows]) {
	self0 := cm.Reinterpret[uint32](self)
	id0 := (uint32)(id)
	wasmimport_TickEarlierRows((uint32)(self0), (uint32)(id0), &result)
	return
}

// Feed represents the imported method "feed".
//
// A hold input's feed as it stands this tick: the same record on
// every tick the source shows on, so a worker that missed the start
// still sees it; none while nothing shows, and on every other input.
// A feed that ends and another that starts within one tick are two
// ticks.
//
//	feed: func(id: u32) -> option<feed>
//
//go:nosplit
func (self Tick) Feed(id uint32) (result cm.Option[Feed]) {
	self0 := cm.Reinterpret[uint32](self)
	id0 := (uint32)(id)
	wasmimport_TickFeed((uint32)(self0), (uint32)(id0), &result)
	return
}

// Fetch represents the imported method "fetch".
//
// Item `index`'s bytes, copied on demand: the only copy of a frame
// kind's payload. Video: one frame's pixels in the stream's format,
// tightly packed. Audio: interleaved samples in its sample format.
//
//	fetch: func(id: u32, index: u32) -> list<u8>
//
//go:nosplit
func (self Tick) Fetch(id uint32, index uint32) (result cm.List[uint8]) {
	self0 := cm.Reinterpret[uint32](self)
	id0 := (uint32)(id)
	index0 := (uint32)(index)
	wasmimport_TickFetch((uint32)(self0), (uint32)(id0), (uint32)(index0), &result)
	return
}

// Frames represents the imported method "frames".
//
// Frame kinds: the frames this tick hands, oldest first. The clock and
// a lockstep input hand their window. A hold input hands the frame it
// shows, or none before its feed's first frame and once its feed has
// ended. Audio hands one frame, the tick's samples re-cut from
// whatever packets arrived; a hold audio input hands none while its
// source is behind, and the node fills the silence. Empty on message
// kinds.
//
//	frames: func(id: u32) -> list<frame>
//
//go:nosplit
func (self Tick) Frames(id uint32) (result cm.List[Frame]) {
	self0 := cm.Reinterpret[uint32](self)
	id0 := (uint32)(id)
	wasmimport_TickFrames((uint32)(self0), (uint32)(id0), &result)
	return
}

// Info represents the imported method "info".
//
// The stream as the host knows it this tick, its time base included.
// A hold input's tags and time base are its current source's, from
// each feed's start on.
//
//	info: func(id: u32) -> stream-info
//
//go:nosplit
func (self Tick) Info(id uint32) (result StreamInfo) {
	self0 := cm.Reinterpret[uint32](self)
	id0 := (uint32)(id)
	wasmimport_TickInfo((uint32)(self0), (uint32)(id0), &result)
	return
}

// Last represents the imported method "last".
//
// Whether this is the instance's final call. It carries whatever the
// inputs have left, which may be nothing, and happens exactly once.
// There is no separate flush.
//
//	last: func() -> bool
//
//go:nosplit
func (self Tick) Last() (result bool) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_TickLast((uint32)(self0))
	result = (bool)(cm.U32ToBool((uint32)(result0)))
	return
}

// Messages represents the imported method "messages".
//
// Data inputs: the messages this tick hands under the input's pairing,
// in pts order, each delivered once. Empty on other kinds.
//
//	messages: func(id: u32) -> list<message>
//
//go:nosplit
func (self Tick) Messages(id uint32) (result cm.List[Message]) {
	self0 := cm.Reinterpret[uint32](self)
	id0 := (uint32)(id)
	wasmimport_TickMessages((uint32)(self0), (uint32)(id0), &result)
	return
}

// Packets represents the imported method "packets".
//
// Packets inputs: the packets this tick hands, in decode order, each
// delivered once. Empty on other kinds.
//
//	packets: func(id: u32) -> list<packet>
//
//go:nosplit
func (self Tick) Packets(id uint32) (result cm.List[Packet]) {
	self0 := cm.Reinterpret[uint32](self)
	id0 := (uint32)(id)
	wasmimport_TickPackets((uint32)(self0), (uint32)(id0), &result)
	return
}

// Pts represents the imported method "pts".
//
// The tick's time in `time-base`. An input clock: its first frame or
// message this call, or the running maximum of dts over a packets
// clock (pts where dts is unset), or, on a last call that hands none,
// the time just past its last. A rate clock: the tick's number, from
// 0. A self-clocked node: microseconds since its first call.
//
//	pts: func() -> s64
//
//go:nosplit
func (self Tick) Pts() (result int64) {
	self0 := cm.Reinterpret[uint32](self)
	result0 := wasmimport_TickPts((uint32)(self0))
	result = (int64)((uint64)(result0))
	return
}

// Streams represents the imported method "streams".
//
// The streams bound to input `port`, in `init`'s order: the same every
// tick, empty for an optional port with nothing bound. A name the
// shape does not declare is a fault.
//
//	streams: func(port: string) -> list<u32>
//
//go:nosplit
func (self Tick) Streams(port string) (result cm.List[uint32]) {
	self0 := cm.Reinterpret[uint32](self)
	port0, port1 := cm.LowerString(port)
	wasmimport_TickStreams((uint32)(self0), (*uint8)(port0), (uint32)(port1), &result)
	return
}

// TimeBase represents the imported method "time-base".
//
// The clock input's time base, the inverse of a rate clock's rate, or
// 1/1000000 for a self-clocked node.
//
//	time-base: func() -> rational
//
//go:nosplit
func (self Tick) TimeBase() (result Rational) {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_TickTimeBase((uint32)(self0), &result)
	return
}
