// Code generated by wit-bindgen-go. DO NOT EDIT.

package types

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// VideoFormatShape is used for storage in variant or result types.
type VideoFormatShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(VideoFormat{})]byte
}
