// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package types represents the imported interface "ffrwd:av/types@0.10.0".
package types

import (
	"go.bytecodealliance.org/cm"
)

// Meta represents the record "ffrwd:av/types@0.10.0#meta".
//
// Static description of a module, available without running anything.
//
//	record meta {
//		name: string,
//		version: string,
//		params-schema: string,
//		rows-schema: string,
//		pixel-formats: list<string>,
//		sample-formats: list<string>,
//		sample-rates: list<u32>,
//		channel-counts: list<u32>,
//		rows-language: list<string>,
//	}
type Meta struct {
	_       cm.HostLayout `json:"-"`
	Name    string        `json:"name"`
	Version string        `json:"version"`

	// JSON Schema for the `params` string.
	ParamsSchema string `json:"params-schema"`

	// JSON Schema for one row object; empty when the module emits none.
	RowsSchema string `json:"rows-schema"`

	// Pixel formats accepted, most preferred first. Empty means this is not
	// a video module.
	PixelFormats cm.List[string] `json:"pixel-formats"`

	// Sample formats accepted, most preferred first: "f32" or "s16", always
	// interleaved. Empty means this is not an audio module. A module is one
	// kind or the other, so exactly one of this and `pixel-formats` is
	// filled in.
	SampleFormats cm.List[string] `json:"sample-formats"`

	// Sample rates accepted. Empty is every rate.
	SampleRates cm.List[uint32] `json:"sample-rates"`

	// Channel counts accepted. Empty is every count.
	ChannelCounts cm.List[uint32] `json:"channel-counts"`

	// Ordered param names; the module's rows' language is the first of these
	// params that is set at the call; empty list = none declared.
	RowsLanguage cm.List[string] `json:"rows-language"`
}

// Rational represents the record "ffrwd:av/types@0.10.0#rational".
//
// A ratio of two whole numbers.
//
//	record rational {
//		num: s32,
//		den: s32,
//	}
type Rational struct {
	_   cm.HostLayout `json:"-"`
	Num int32         `json:"num"`
	Den int32         `json:"den"`
}

// VideoFormat represents the record "ffrwd:av/types@0.10.0#video-format".
//
// The frames of a video instance, fixed for the life of the instance.
//
//	record video-format {
//		width: u32,
//		height: u32,
//		pix-fmt: string,
//	}
type VideoFormat struct {
	_      cm.HostLayout `json:"-"`
	Width  uint32        `json:"width"`
	Height uint32        `json:"height"`
	PixFmt string        `json:"pix-fmt"`
}

// AudioFormat represents the record "ffrwd:av/types@0.10.0#audio-format".
//
// The samples of an audio instance, fixed for the life of the instance.
//
//	record audio-format {
//		sample-rate: u32,
//		channels: u32,
//		sample-fmt: string,
//	}
type AudioFormat struct {
	_          cm.HostLayout `json:"-"`
	SampleRate uint32        `json:"sample-rate"`
	Channels   uint32        `json:"channels"`

	// "f32" or "s16", interleaved.
	SampleFmt string `json:"sample-fmt"`
}

// Format represents the variant "ffrwd:av/types@0.10.0#format".
//
// What an instance is opened for, which is what tells its kind. A module
// is handed the arm its own declaration asked for; the host refuses the
// other one before `init`.
//
//	variant format {
//		video(video-format),
//		audio(audio-format),
//	}
type Format cm.Variant[uint8, VideoFormatShape, VideoFormat]

// FormatVideo returns a [Format] of case "video".
func FormatVideo(data VideoFormat) Format {
	return cm.New[Format](0, data)
}

// Video returns a non-nil *[VideoFormat] if [Format] represents the variant case "video".
func (self *Format) Video() *VideoFormat {
	return cm.Case[VideoFormat](self, 0)
}

// FormatAudio returns a [Format] of case "audio".
func FormatAudio(data AudioFormat) Format {
	return cm.New[Format](1, data)
}

// Audio returns a non-nil *[AudioFormat] if [Format] represents the variant case "audio".
func (self *Format) Audio() *AudioFormat {
	return cm.Case[AudioFormat](self, 1)
}

var _FormatStrings = [2]string{
	"video",
	"audio",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Format) String() string {
	return _FormatStrings[v.Tag()]
}

// StreamInfo represents the record "ffrwd:av/types@0.10.0#stream-info".
//
// The stream an instance is attached to, told once at init.
//
//	record stream-info {
//		index: u32,
//		kind: string,
//		codec: string,
//		duration: option<f64>,
//		tags: list<tuple<string, string>>,
//		time-base: rational,
//	}
type StreamInfo struct {
	_     cm.HostLayout `json:"-"`
	Index uint32        `json:"index"`
	Kind  string        `json:"kind"`
	Codec string        `json:"codec"`

	// Seconds; absent when unknown.
	Duration cm.Option[float64] `json:"duration"`

	// The stream's own tags.
	Tags cm.List[[2]string] `json:"tags"`

	// The unit timestamps are counted in, as a fraction of a second. The host
	// always supplies it; `den` is always positive. A windowed module is
	// handed timestamps rather than seconds, so this is how one whose
	// parameters are in seconds converts them. For audio it is what turns a
	// sample position into a timestamp: at 1/48000 one tick is one sample.
	TimeBase Rational `json:"time-base"`
}
