// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package types represents the imported interface "ffrwd:av/types@0.19.0".
package types

import (
	"go.bytecodealliance.org/cm"
)

// Meta represents the record "ffrwd:av/types@0.19.0#meta".
//
// Static description of a module, available without running anything.
//
//	record meta {
//		name: string,
//		version: string,
//		params-schema: string,
//		rows-schema: string,
//		pixel-formats: list<string>,
//		sample-formats: list<string>,
//		sample-rates: list<u32>,
//		channel-counts: list<u32>,
//		rows-language: list<string>,
//	}
type Meta struct {
	_       cm.HostLayout `json:"-"`
	Name    string        `json:"name"`
	Version string        `json:"version"`

	// JSON Schema for the `params` string.
	ParamsSchema string `json:"params-schema"`

	// JSON Schema for one row object; empty when the module emits none.
	RowsSchema string `json:"rows-schema"`

	// Pixel formats accepted, most preferred first. Empty means this is not
	// a video module.
	PixelFormats cm.List[string] `json:"pixel-formats"`

	// Sample formats accepted, most preferred first: "f32" or "s16", always
	// interleaved. Empty means this is not an audio module. A module is one
	// kind or the other, so exactly one of this and `pixel-formats` is
	// filled in.
	SampleFormats cm.List[string] `json:"sample-formats"`

	// Sample rates accepted. Empty is every rate.
	SampleRates cm.List[uint32] `json:"sample-rates"`

	// Channel counts accepted. Empty is every count.
	ChannelCounts cm.List[uint32] `json:"channel-counts"`

	// Ordered param names; the module's rows' language is the first of these
	// params that is set at the call; empty list = none declared.
	RowsLanguage cm.List[string] `json:"rows-language"`
}

// Rational represents the record "ffrwd:av/types@0.19.0#rational".
//
// A ratio of two whole numbers.
//
//	record rational {
//		num: s32,
//		den: s32,
//	}
type Rational struct {
	_   cm.HostLayout `json:"-"`
	Num int32         `json:"num"`
	Den int32         `json:"den"`
}

// ColorInfo represents the record "ffrwd:av/types@0.19.0#color-info".
//
// A stream's colorimetry, in ffmpeg's own names: "tv" or "pc" for the
// range, "bt709" and the like for the rest. A field the wire does not
// settle is "unknown", ffmpeg's own spelling for it.
//
//	record color-info {
//		range: string,
//		primaries: string,
//		trc: string,
//		space: string,
//	}
type ColorInfo struct {
	_         cm.HostLayout `json:"-"`
	Range     string        `json:"range"`
	Primaries string        `json:"primaries"`
	Trc       string        `json:"trc"`
	Space     string        `json:"space"`
}

// VideoFormat represents the record "ffrwd:av/types@0.19.0#video-format".
//
// The frames of a video instance, fixed for the life of the instance.
// Frames cross this boundary square-pixel: the host rescales anamorphic
// input before it arrives, so no aspect ratio is carried here.
//
//	record video-format {
//		width: u32,
//		height: u32,
//		pix-fmt: string,
//		color: option<color-info>,
//	}
type VideoFormat struct {
	_      cm.HostLayout `json:"-"`
	Width  uint32        `json:"width"`
	Height uint32        `json:"height"`
	PixFmt string        `json:"pix-fmt"`

	// The colorimetry the stream header declared; none where it did not.
	Color cm.Option[ColorInfo] `json:"color"`
}

// AudioFormat represents the record "ffrwd:av/types@0.19.0#audio-format".
//
// The samples of an audio instance, fixed for the life of the instance.
//
//	record audio-format {
//		sample-rate: u32,
//		channels: u32,
//		sample-fmt: string,
//		channel-layout: option<string>,
//	}
type AudioFormat struct {
	_          cm.HostLayout `json:"-"`
	SampleRate uint32        `json:"sample-rate"`
	Channels   uint32        `json:"channels"`

	// "f32" or "s16", interleaved.
	SampleFmt string `json:"sample-fmt"`

	// ffmpeg's name for the channel layout ("stereo", "5.1"), which a
	// count alone cannot say; none where the wire does not carry one.
	ChannelLayout cm.Option[string] `json:"channel-layout"`
}

// Format represents the variant "ffrwd:av/types@0.19.0#format".
//
// What an instance is opened for, which is what tells its kind. A module
// is handed the arm its own declaration asked for; the host refuses the
// other one before `init`.
//
//	variant format {
//		video(video-format),
//		audio(audio-format),
//	}
type Format cm.Variant[uint8, VideoFormatShape, VideoFormat]

// FormatVideo returns a [Format] of case "video".
func FormatVideo(data VideoFormat) Format {
	return cm.New[Format](0, data)
}

// Video returns a non-nil *[VideoFormat] if [Format] represents the variant case "video".
func (self *Format) Video() *VideoFormat {
	return cm.Case[VideoFormat](self, 0)
}

// FormatAudio returns a [Format] of case "audio".
func FormatAudio(data AudioFormat) Format {
	return cm.New[Format](1, data)
}

// Audio returns a non-nil *[AudioFormat] if [Format] represents the variant case "audio".
func (self *Format) Audio() *AudioFormat {
	return cm.Case[AudioFormat](self, 1)
}

var _FormatStrings = [2]string{
	"video",
	"audio",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Format) String() string {
	return _FormatStrings[v.Tag()]
}

// StreamInfo represents the record "ffrwd:av/types@0.19.0#stream-info".
//
// The stream an instance is attached to, told once at init.
//
//	record stream-info {
//		index: u32,
//		kind: string,
//		codec: string,
//		duration: option<f64>,
//		tags: list<tuple<string, string>>,
//		time-base: rational,
//	}
type StreamInfo struct {
	_     cm.HostLayout `json:"-"`
	Index uint32        `json:"index"`
	Kind  string        `json:"kind"`
	Codec string        `json:"codec"`

	// Seconds; absent when unknown.
	Duration cm.Option[float64] `json:"duration"`

	// The stream's own tags.
	Tags cm.List[[2]string] `json:"tags"`

	// The unit timestamps are counted in, as a fraction of a second. The host
	// always supplies it; `den` is always positive. A windowed module is
	// handed timestamps rather than seconds, so this is how one whose
	// parameters are in seconds converts them. For audio it is what turns a
	// sample position into a timestamp: at 1/48000 one tick is one sample.
	TimeBase Rational `json:"time-base"`
}

// CodedVideo represents the record "ffrwd:av/types@0.19.0#coded-video".
//
// The frames a coded video stream declares. Shared between `packet-sink`
// and `packet-source`.
//
//	record coded-video {
//		width: u32,
//		height: u32,
//		sample-aspect-ratio: option<rational>,
//		color: option<color-info>,
//	}
type CodedVideo struct {
	_      cm.HostLayout `json:"-"`
	Width  uint32        `json:"width"`
	Height uint32        `json:"height"`

	// The pixel aspect ratio the stream declares. Packets cannot be
	// host-rescaled, so a packager writes it through (mp4's `pasp`);
	// none where the wire does not say.
	SampleAspectRatio cm.Option[Rational] `json:"sample-aspect-ratio"`

	// The colorimetry the stream header declared; none where it did not.
	Color cm.Option[ColorInfo] `json:"color"`
}

// CodedAudio represents the record "ffrwd:av/types@0.19.0#coded-audio".
//
// The samples a coded audio stream declares.
//
//	record coded-audio {
//		sample-rate: u32,
//		channels: u32,
//		channel-layout: option<string>,
//	}
type CodedAudio struct {
	_          cm.HostLayout `json:"-"`
	SampleRate uint32        `json:"sample-rate"`
	Channels   uint32        `json:"channels"`

	// ffmpeg's name for the channel layout ("stereo", "5.1"), which a
	// count alone cannot say; none where the wire does not carry one.
	ChannelLayout cm.Option[string] `json:"channel-layout"`
}

// CodedFormat represents the variant "ffrwd:av/types@0.19.0#coded-format".
//
// What a coded stream carries, which is what tells its kind.
//
//	variant coded-format {
//		video(coded-video),
//		audio(coded-audio),
//		data,
//	}
type CodedFormat cm.Variant[uint8, CodedVideoShape, CodedVideo]

// CodedFormatVideo returns a [CodedFormat] of case "video".
func CodedFormatVideo(data CodedVideo) CodedFormat {
	return cm.New[CodedFormat](0, data)
}

// Video returns a non-nil *[CodedVideo] if [CodedFormat] represents the variant case "video".
func (self *CodedFormat) Video() *CodedVideo {
	return cm.Case[CodedVideo](self, 0)
}

// CodedFormatAudio returns a [CodedFormat] of case "audio".
func CodedFormatAudio(data CodedAudio) CodedFormat {
	return cm.New[CodedFormat](1, data)
}

// Audio returns a non-nil *[CodedAudio] if [CodedFormat] represents the variant case "audio".
func (self *CodedFormat) Audio() *CodedAudio {
	return cm.Case[CodedAudio](self, 1)
}

// CodedFormatData returns a [CodedFormat] of case "data".
//
// A data stream: messages rather than pictures or sound, each packet
// one message at its own pts. For codec "json" a message is one UTF-8
// JSON object. It has no geometry, and every packet is a keyframe.
func CodedFormatData() CodedFormat {
	var data struct{}
	return cm.New[CodedFormat](2, data)
}

// Data returns true if [CodedFormat] represents the variant case "data".
func (self *CodedFormat) Data() bool {
	return self.Tag() == 2
}

var _CodedFormatStrings = [3]string{
	"video",
	"audio",
	"data",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v CodedFormat) String() string {
	return _CodedFormatStrings[v.Tag()]
}

// CodedStream represents the record "ffrwd:av/types@0.19.0#coded-stream".
//
// One encoded stream an instance is opened for, fixed for its life.
//
//	record coded-stream {
//		codec: string,
//		time-base: rational,
//		format: coded-format,
//		extradata: list<u8>,
//		profile: option<s32>,
//		level: option<s32>,
//	}
type CodedStream struct {
	_ cm.HostLayout `json:"-"`
	// ffmpeg's name for the codec, e.g. "h264".
	Codec string `json:"codec"`

	// The unit `pts` and `dts` are counted in, as a fraction of a second.
	TimeBase Rational `json:"time-base"`

	// The geometry the stream declares, and its kind.
	Format CodedFormat `json:"format"`

	// The codec's out-of-band header, exactly as the stream header carried
	// it: for h264, the SPS and PPS a downstream packager needs before the
	// first packet.
	Extradata cm.List[uint8] `json:"extradata"`

	// The codec's profile, in the codec's own numbering - what ffmpeg's
	// codec parameters carry; none where the wire does not say.
	Profile cm.Option[int32] `json:"profile"`

	// The codec's level, likewise.
	Level cm.Option[int32] `json:"level"`
}

// Packet represents the record "ffrwd:av/types@0.19.0#packet".
//
// One encoded packet, exactly as the encoder emitted it.
//
//	record packet {
//		pts: s64,
//		dts: option<s64>,
//		duration: option<s64>,
//		keyframe: bool,
//		data: list<u8>,
//	}
type Packet struct {
	_ cm.HostLayout `json:"-"`
	// When the picture is presented, in the stream's time base. Packets
	// arrive in decode order, so where the stream reorders frames this is
	// not monotonic.
	Pts int64 `json:"pts"`

	// When the packet is decoded; never decreasing. Absent for the first
	// packets of a reordering stream, where the wire does not settle it.
	Dts cm.Option[int64] `json:"dts"`

	// How long the packet is presented, in the stream's time base: the
	// next packet's pts minus this one's, in presentation order. None
	// where the wire does not settle it - unknown is never spelled 0.
	Duration cm.Option[int64] `json:"duration"`

	// Whether decoding can start at this packet.
	Keyframe bool `json:"keyframe"`

	// The encoded bytes, untouched.
	Data cm.List[uint8] `json:"data"`
}

// RawFrame represents the record "ffrwd:av/types@0.19.0#raw-frame".
//
// One raw frame crossing a codec: a video frame's pixels in the
// instance's pix-fmt, or a run of interleaved audio samples in its
// sample-fmt. What a codec and a node hand over.
//
//	record raw-frame {
//		pts: s64,
//		duration: option<s64>,
//		data: list<u8>,
//	}
type RawFrame struct {
	_ cm.HostLayout `json:"-"`
	// When it is presented, in the stream's time base.
	Pts int64 `json:"pts"`

	// How long it is presented, in the stream's time base; none where
	// nothing settles it - unknown is never spelled 0.
	Duration cm.Option[int64] `json:"duration"`
	Data     cm.List[uint8]   `json:"data"`
}

// PadPackets represents the record "ffrwd:av/types@0.19.0#pad-packets".
//
// One pad's packets from one call, in decode order. Empty when nothing
// arrived on that pad; a packet sink's list of these is as long as its
// `init`'s streams and in the same order, so the index is the pad.
//
//	record pad-packets {
//		packets: list<packet>,
//	}
type PadPackets struct {
	_       cm.HostLayout   `json:"-"`
	Packets cm.List[Packet] `json:"packets"`
}

// RenditionMeta represents the record "ffrwd:av/types@0.19.0#rendition-meta".
//
// What the source read of one relation row: a rendition's name, bitrate
// and codec string, exactly as the manifest or catalog said them. None
// where nothing said so. Shared between `packet-sink` and
// `packet-source`.
//
//	record rendition-meta {
//		name: option<string>,
//		bandwidth: option<u64>,
//		codecs: option<string>,
//		language: option<string>,
//	}
type RenditionMeta struct {
	_         cm.HostLayout     `json:"-"`
	Name      cm.Option[string] `json:"name"`
	Bandwidth cm.Option[uint64] `json:"bandwidth"`
	Codecs    cm.Option[string] `json:"codecs"`
	Language  cm.Option[string] `json:"language"`
}

// Wants represents the enum "ffrwd:av/types@0.19.0#wants".
//
// How much of a stream a sink has to be handed to do its work. A sink
// that reads what a writer put on keyframes, or what a stream's first
// packet declares, does not need the rest - and a host reading a file to
// answer a question at compile time can copy far less of it.
//
// It is a REQUEST, not a promise: a host may hand over more than was
// asked for, and every sink has to work when it does. What a host may not
// do is hand over less.
//
//	enum wants {
//		all,
//		keyframes,
//		first
//	}
type Wants uint8

const (
	// Every packet of every stream. What a sink that counts, tallies or
	// republishes needs, and what a host with no way to skip hands over.
	WantsAll Wants = iota

	// The keyframes, and whatever else the host could not cheaply drop.
	// What a sink reading data a writer placed on keyframes needs.
	WantsKeyframes

	// The first packet of each stream, and no more. What a sink reading
	// only what a stream declares about itself needs.
	WantsFirst
)

var _WantsStrings = [3]string{
	"all",
	"keyframes",
	"first",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e Wants) String() string {
	return _WantsStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e Wants) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *Wants) UnmarshalText(text []byte) error {
	return _WantsUnmarshalCase(e, text)
}

var _WantsUnmarshalCase = cm.CaseUnmarshaler[Wants](_WantsStrings[:])

// Arity represents the enum "ffrwd:av/types@0.19.0#arity".
//
// How many streams of one kind a module reading encoded packets takes.
// Shared between `packet-sink` and `packet-filter`.
//
//	enum arity {
//		zero,
//		one,
//		many,
//		any
//	}
type Arity uint8

const (
	// None of this kind reaches the module.
	ArityZero Arity = iota

	// Exactly one, which is what every sink before 0.12.0 read.
	ArityOne

	// One or more, as many as the query hands over.
	ArityMany

	// As many as the query hands over, none included: the module reads
	// them when they are there and works when they are not.
	ArityAny
)

var _ArityStrings = [4]string{
	"zero",
	"one",
	"many",
	"any",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e Arity) String() string {
	return _ArityStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e Arity) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *Arity) UnmarshalText(text []byte) error {
	return _ArityUnmarshalCase(e, text)
}

var _ArityUnmarshalCase = cm.CaseUnmarshaler[Arity](_ArityStrings[:])

// InputStream represents the record "ffrwd:av/types@0.19.0#input-stream".
//
// One pad's stream, told once at init: what the wire's own header said
// about the encoding, and what the process driving the host said about
// the stream. Shared between `packet-sink` and `packet-filter`.
//
//	record input-stream {
//		coded: coded-stream,
//		info: stream-info,
//		row: u32,
//		rendition: rendition-meta,
//		decode-delay: u32,
//	}
type InputStream struct {
	_     cm.HostLayout `json:"-"`
	Coded CodedStream   `json:"coded"`
	Info  StreamInfo    `json:"info"`

	// Which relation row this pad belongs to - the moq sink learns
	// renditions from the rows instead of from argument names.
	Row uint32 `json:"row"`

	// What the source read of that row.
	Rendition RenditionMeta `json:"rendition"`

	// How deep this stream reorders: how many packets the decoder holds
	// back before the first picture leaves it. 0 where decode order IS
	// presentation order, and higher wherever B-frames do.
	//
	// It is the bound a module that must see packets in PRESENTATION
	// order works with: a packet's presentation successor has arrived
	// once `decode-delay` more packets have. It is also why `packet.dts`
	// is none for a pad's first `decode-delay` packets, which is the wire
	// not having settled them rather than the host withholding them.
	DecodeDelay uint32 `json:"decode-delay"`
}
