// Code generated by wit-bindgen-go. DO NOT EDIT.

package windowfilter

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "ffrwd:av/window-filter@0.10.0".
var Exports struct {
	// Describe represents the caller-defined, exported function "describe".
	//
	//	describe: func() -> window-meta
	Describe func() (result WindowMeta)

	// Init represents the caller-defined, exported function "init".
	//
	// Called once per instance. The arm of `format` is the one the module's
	// own declaration asked for: a module publishing pixel formats is opened
	// with `video`, one publishing sample formats with `audio`.
	//
	//	init: func(format: format, stream-info: stream-info, params: string) -> result<_,
	//	string>
	Init func(format Format, streamInfo StreamInfo, params string) (result cm.Result[string, struct{}, string])

	// SetParams represents the caller-defined, exported function "set-params".
	//
	// Replaces the parameters between windows, as `filter`'s does.
	//
	//	set-params: func(params: string) -> result<_, string>
	SetParams func(params string) (result cm.Result[string, struct{}, string])

	// Process represents the caller-defined, exported function "process".
	//
	// One window. `last` marks the final call of the instance's life: it
	// carries whatever the last stride left over, which may be nothing, and
	// happens exactly once. There is no separate flush.
	//
	// `frames` is the window for a module reading one stream. For a module
	// reading several it is one frame per pad, in pad order, every one of them
	// at the same pts - which is why such a module is window 1, stride 1.
	//
	// `trailing` is the rows an upstream module had nothing to put them on;
	// only the last call carries any. Like `rows`, it follows pad 0: what
	// reached the other pads with nothing to ride never arrives here.
	//
	// Output timestamps never decrease, within a call or between calls.
	//
	//	process: func(frames: list<in-frame>, trailing: list<string>, last: bool) -> processed
	Process func(frames cm.List[InFrame], trailing cm.List[string], last bool) (result Processed)
}
