// Code generated by wit-bindgen-go. DO NOT EDIT.

package windowfilter

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "ffrwd:av@0.10.0".

//go:wasmexport ffrwd:av/window-filter@0.10.0#describe
//export ffrwd:av/window-filter@0.10.0#describe
func wasmexport_Describe() (result *WindowMeta) {
	result_ := Exports.Describe()
	result = &result_
	return
}

//go:wasmexport ffrwd:av/window-filter@0.10.0#init
//export ffrwd:av/window-filter@0.10.0#init
func wasmexport_Init(params *wasmexport_Init_params) (result *cm.Result[string, struct{}, string]) {
	result_ := Exports.Init(params.format, params.streamInfo, params.params)
	result = &result_
	return
}

//go:wasmexport ffrwd:av/window-filter@0.10.0#set-params
//export ffrwd:av/window-filter@0.10.0#set-params
func wasmexport_SetParams(params0 *uint8, params1 uint32) (result *cm.Result[string, struct{}, string]) {
	params := cm.LiftString[string]((*uint8)(params0), (uint32)(params1))
	result_ := Exports.SetParams(params)
	result = &result_
	return
}

//go:wasmexport ffrwd:av/window-filter@0.10.0#process
//export ffrwd:av/window-filter@0.10.0#process
func wasmexport_Process(frames0 *InFrame, frames1 uint32, trailing0 *string, trailing1 uint32, last0 uint32) (result *Processed) {
	frames := cm.LiftList[cm.List[InFrame]]((*InFrame)(frames0), (uint32)(frames1))
	trailing := cm.LiftList[cm.List[string]]((*string)(trailing0), (uint32)(trailing1))
	last := (bool)(cm.U32ToBool((uint32)(last0)))
	result_ := Exports.Process(frames, trailing, last)
	result = &result_
	return
}
