// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package windowfilter represents the exported interface "ffrwd:av/window-filter@0.10.0".
//
// A window at a time, superseding `filter`'s per-frame `process` and
// `meta-filter`'s `process-meta`. A module exports this one *or* those; a
// host adapts a module that exports the older pair as window 1, stride 1,
// one-to-one. `describe`, `init` and `set-params` mean here what they mean
// there, so the two differ only in how the payload arrives and leaves.
//
// This is the only interface audio reaches. `init` is handed a `format`, and
// which arm it carries is the instance's kind for the rest of its life.
package windowfilter

import (
	"github.com/imbcmdth/ffrwd/sidecar/modules-go/internal/ffrwd/av/types"
	"go.bytecodealliance.org/cm"
)

// Format represents the type alias "ffrwd:av/window-filter@0.10.0#format".
//
// See [types.Format] for more information.
type Format = types.Format

// Meta represents the type alias "ffrwd:av/window-filter@0.10.0#meta".
//
// See [types.Meta] for more information.
type Meta = types.Meta

// StreamInfo represents the type alias "ffrwd:av/window-filter@0.10.0#stream-info".
//
// See [types.StreamInfo] for more information.
type StreamInfo = types.StreamInfo

// InFrame represents the record "ffrwd:av/window-filter@0.10.0#in-frame".
//
// One input payload: its timestamp, its bytes, and the rows that arrived
// with it - each an NDJSON line an upstream module produced, empty when
// nothing came with it.
//
// For a video instance the bytes are one frame's pixels. For an audio
// instance they are interleaved samples in the instance's sample format,
// the whole window in one contiguous piece: the host re-cuts whatever
// packets arrived, so a module never sees a packet boundary. `pts` is the
// first sample's tick.
//
// Rows ride pad 0. A module reading several streams is handed whatever
// arrived on pad 0 here, and the rows that arrived on any other pad are
// dropped before the call - so `rows` is empty on every pad past the
// first.
//
//	record in-frame {
//		pts: s64,
//		frame: list<u8>,
//		rows: list<string>,
//	}
type InFrame struct {
	_     cm.HostLayout   `json:"-"`
	Pts   int64           `json:"pts"`
	Frame cm.List[uint8]  `json:"frame"`
	Rows  cm.List[string] `json:"rows"`
}

// FramePayload represents the variant "ffrwd:av/window-filter@0.10.0#frame-payload".
//
// Where an output payload's bytes come from.
//
//	variant frame-payload {
//		new(list<u8>),
//		same,
//	}
type FramePayload cm.Variant[uint8, cm.List[uint8], cm.List[uint8]]

// FramePayloadNew returns a [FramePayload] of case "new".
//
// New bytes: one frame's pixels, or interleaved samples.
func FramePayloadNew(data cm.List[uint8]) FramePayload {
	return cm.New[FramePayload](0, data)
}

// New returns a non-nil *[cm.List[uint8]] if [FramePayload] represents the variant case "new".
func (self *FramePayload) New() *cm.List[uint8] {
	return cm.Case[cm.List[uint8]](self, 0)
}

// FramePayloadSame returns a [FramePayload] of case "same".
//
// An input's bytes, which the module never copied out: the input this
// call received at the same pts, or - when the call received exactly one
// input - that one, whatever pts the output carries. For a module
// reading several streams this is pad 0's bytes, since every pad shares
// the call's one pts. An audio module may say this only when its stride
// is its window, since overlapping windows passed through would emit
// every sample more than once.
func FramePayloadSame() FramePayload {
	var data struct{}
	return cm.New[FramePayload](1, data)
}

// Same returns true if [FramePayload] represents the variant case "same".
func (self *FramePayload) Same() bool {
	return self.Tag() == 1
}

var _FramePayloadStrings = [2]string{
	"new",
	"same",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v FramePayload) String() string {
	return _FramePayloadStrings[v.Tag()]
}

// OutFrame represents the record "ffrwd:av/window-filter@0.10.0#out-frame".
//
// One output. Its pts is the module's to choose: a module may move its
// payload in time, drop it, or emit several from one.
//
//	record out-frame {
//		pts: s64,
//		frame: frame-payload,
//		rows: list<string>,
//	}
type OutFrame struct {
	_     cm.HostLayout   `json:"-"`
	Pts   int64           `json:"pts"`
	Frame FramePayload    `json:"frame"`
	Rows  cm.List[string] `json:"rows"`
}

// WindowMeta represents the record "ffrwd:av/window-filter@0.10.0#window-meta".
//
// `meta`, plus how the host must drive this module.
//
//	record window-meta {
//		meta: meta,
//		window: u32,
//		stride: u32,
//		pure: bool,
//		one-to-one: bool,
//		reads-rows: bool,
//		forwards-rows: bool,
//		inputs: u32,
//	}
type WindowMeta struct {
	_    cm.HostLayout `json:"-"`
	Meta Meta          `json:"meta"`

	// What one `process` call receives: frames for a video module, SAMPLES
	// for an audio one. 1 is plain streaming for video; an audio module
	// names a chunk it is happy to work in, and the host cuts that chunk out
	// of whatever packets arrive.
	Window uint32 `json:"window"`

	// How much is consumed per call, never more than `window`, in the same
	// unit. `window` makes the windows disjoint.
	Stride uint32 `json:"stride"`

	// Whether a call depends only on what it was handed. False makes
	// parallel hosting unsound and a host must refuse it.
	Pure bool `json:"pure"`

	// For video: whether every call returns exactly one output per frame it
	// consumed, each at that frame's own pts. For audio: whether the samples
	// leaving over the instance's life are the samples that arrived, neither
	// dropped nor invented - per-call counts may differ, but the output runs
	// on without gap or overlap. Neither window nor stride settles this, so
	// it is declared.
	OneToOne bool `json:"one-to-one"`

	// Whether this module ACTS on the rows arriving with its payloads. Every
	// call receives them whatever this says, so availability is no answer: a
	// module that only carries rows through declares false, and one that
	// reads what an upstream module detected declares true.
	ReadsRows bool `json:"reads-rows"`

	// Whether upstream rows may appear on this module's own output. False
	// means the rows leaving are the module's own, or none. It speaks of pad
	// 0: rows arrive there and nowhere else.
	ForwardsRows bool `json:"forwards-rows"`

	// How many streams this module reads. Frames arrive one per pad, in pad
	// order, all at the same pts. 1 is the ordinary module, reading one
	// stream. More than 1 is window 1, stride 1 - a call takes one frame off
	// each pad and hands one back - and a host refuses any other shape.
	Inputs uint32 `json:"inputs"`
}

// Processed represents the record "ffrwd:av/window-filter@0.10.0#processed".
//
// What one call produced.
//
//	record processed {
//		frames: list<out-frame>,
//		trailing: list<string>,
//	}
type Processed struct {
	_      cm.HostLayout     `json:"-"`
	Frames cm.List[OutFrame] `json:"frames"`

	// Rows with nothing to ride. Only the last call may fill this.
	Trailing cm.List[string] `json:"trailing"`
}

// wasmexport_Init_params represents the flattened function params for [wasmexport_Init].
// See the Canonical ABI flattening rules for more information.
type wasmexport_Init_params struct {
	_          cm.HostLayout `json:"-"`
	format     Format        `json:"format"`
	streamInfo StreamInfo    `json:"stream-info"`
	params     string        `json:"params"`
}
