// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     ffrwd:av@0.10.0
//     wasi:io@0.2.0
//     wasi:clocks@0.2.0
//     wasi:filesystem@0.2.0
//     wasi:sockets@0.2.0
//     wasi:random@0.2.0
//     wasi:cli@0.2.0
//     ffrwd:av-go@0.1.0

package wasi_cli_terminal_output

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	"runtime"
)

//go:wasmimport wasi:cli/terminal-output@0.2.0 [resource-drop]terminal-output
func resourceDropTerminalOutput(handle int32)

// The output side of a terminal.
type TerminalOutput struct {
	handle *witRuntime.Handle
}

func (self *TerminalOutput) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *TerminalOutput) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *TerminalOutput) Handle() int32 {
	return self.handle.Use()
}

func (self *TerminalOutput) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropTerminalOutput(handle)
	}
}

func TerminalOutputFromOwnHandle(handleValue int32) *TerminalOutput {
	handle := witRuntime.MakeHandle(handleValue)
	value := &TerminalOutput{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropTerminalOutput(handleValue)
		}
	}, 0)
	return value
}

func TerminalOutputFromBorrowHandle(handleValue int32) *TerminalOutput {
	handle := witRuntime.MakeHandle(handleValue)
	return &TerminalOutput{handle}
}
