// Code generated by wit-bindgen-go. DO NOT EDIT.

package nodetypes

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// HoldShape is used for storage in variant or result types.
type HoldShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Hold{})]byte
}

// CodedStreamShape is used for storage in variant or result types.
type CodedStreamShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(CodedStream{})]byte
}
