// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package nodetypes represents the imported interface "ffrwd:av/node-types@0.19.0".
package nodetypes

import (
	"github.com/imbcmdth/ffrwd/sidecar/modules-go/internal/ffrwd/av/types"
	"go.bytecodealliance.org/cm"
)

// Rational represents the type alias "ffrwd:av/node-types@0.19.0#rational".
//
// See [types.Rational] for more information.
type Rational = types.Rational

// ColorInfo represents the type alias "ffrwd:av/node-types@0.19.0#color-info".
//
// See [types.ColorInfo] for more information.
type ColorInfo = types.ColorInfo

// VideoFormat represents the type alias "ffrwd:av/node-types@0.19.0#video-format".
//
// See [types.VideoFormat] for more information.
type VideoFormat = types.VideoFormat

// AudioFormat represents the type alias "ffrwd:av/node-types@0.19.0#audio-format".
//
// See [types.AudioFormat] for more information.
type AudioFormat = types.AudioFormat

// CodedStream represents the type alias "ffrwd:av/node-types@0.19.0#coded-stream".
//
// See [types.CodedStream] for more information.
type CodedStream = types.CodedStream

// Packet represents the type alias "ffrwd:av/node-types@0.19.0#packet".
//
// See [types.Packet] for more information.
type Packet = types.Packet

// StreamInfo represents the type alias "ffrwd:av/node-types@0.19.0#stream-info".
//
// See [types.StreamInfo] for more information.
type StreamInfo = types.StreamInfo

// RenditionMeta represents the type alias "ffrwd:av/node-types@0.19.0#rendition-meta".
//
// See [types.RenditionMeta] for more information.
type RenditionMeta = types.RenditionMeta

// Wants represents the type alias "ffrwd:av/node-types@0.19.0#wants".
//
// See [types.Wants] for more information.
type Wants = types.Wants

// PortKind represents the enum "ffrwd:av/node-types@0.19.0#port-kind".
//
//	enum port-kind {
//		video,
//		audio,
//		data,
//		packets
//	}
type PortKind uint8

const (
	PortKindVideo PortKind = iota
	PortKindAudio
	PortKindData
	PortKindPackets
)

var _PortKindStrings = [4]string{
	"video",
	"audio",
	"data",
	"packets",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e PortKind) String() string {
	return _PortKindStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e PortKind) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *PortKind) UnmarshalText(text []byte) error {
	return _PortKindUnmarshalCase(e, text)
}

var _PortKindUnmarshalCase = cm.CaseUnmarshaler[PortKind](_PortKindStrings[:])

// RowsUse represents the enum "ffrwd:av/node-types@0.19.0#rows-use".
//
// What a node does with the rows that arrive on an input.
// `per-frame`: reads a tick's rows while handling that tick and keeps
// nothing. `state`: folds rows into state later ticks depend on, so a
// frame-parallel instance must also see the rows of the ticks it did not
// process (`earlier-rows`).
//
//	enum rows-use {
//		ignore,
//		per-frame,
//		state
//	}
type RowsUse uint8

const (
	RowsUseIgnore RowsUse = iota
	RowsUsePerFrame
	RowsUseState
)

var _RowsUseStrings = [3]string{
	"ignore",
	"per-frame",
	"state",
}

// String implements [fmt.Stringer], returning the enum case name of e.
func (e RowsUse) String() string {
	return _RowsUseStrings[e]
}

// MarshalText implements [encoding.TextMarshaler].
func (e RowsUse) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

// UnmarshalText implements [encoding.TextUnmarshaler], unmarshaling into an enum
// case. Returns an error if the supplied text is not one of the enum cases.
func (e *RowsUse) UnmarshalText(text []byte) error {
	return _RowsUseUnmarshalCase(e, text)
}

var _RowsUseUnmarshalCase = cm.CaseUnmarshaler[RowsUse](_RowsUseStrings[:])

// Anchor represents the variant "ffrwd:av/node-types@0.19.0#anchor".
//
// How a hold input's offset between source time and clock time is fixed.
// `shared-clock`: the source's pts are on the clock's epoch; offset 0, and
// the host holds the first frame until the clock reaches it (a timed
// feeder). `first-frame`: the offset is fixed once the host holds `lead`
// seconds of the source, or its end, and the start is scheduled `lead`
// seconds ahead of the clock (an untimed feeder). `tagged`: shared-clock
// for a feed whose tags carry this name set to 1, first-frame
// otherwise (the switch's `smart_timed`).
//
//	variant anchor {
//		shared-clock,
//		first-frame,
//		tagged(string),
//	}
type Anchor cm.Variant[uint8, string, string]

// AnchorSharedClock returns a [Anchor] of case "shared-clock".
func AnchorSharedClock() Anchor {
	var data struct{}
	return cm.New[Anchor](0, data)
}

// SharedClock returns true if [Anchor] represents the variant case "shared-clock".
func (self *Anchor) SharedClock() bool {
	return self.Tag() == 0
}

// AnchorFirstFrame returns a [Anchor] of case "first-frame".
func AnchorFirstFrame() Anchor {
	var data struct{}
	return cm.New[Anchor](1, data)
}

// FirstFrame returns true if [Anchor] represents the variant case "first-frame".
func (self *Anchor) FirstFrame() bool {
	return self.Tag() == 1
}

// AnchorTagged returns a [Anchor] of case "tagged".
func AnchorTagged(data string) Anchor {
	return cm.New[Anchor](2, data)
}

// Tagged returns a non-nil *[string] if [Anchor] represents the variant case "tagged".
func (self *Anchor) Tagged() *string {
	return cm.Case[string](self, 2)
}

var _AnchorStrings = [3]string{
	"shared-clock",
	"first-frame",
	"tagged",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Anchor) String() string {
	return _AnchorStrings[v.Tag()]
}

// Hold represents the record "ffrwd:av/node-types@0.19.0#hold".
//
// A frame input paired by time: the newest frame at or before the tick.
// The host keeps the source buffered ahead, repeats the last frame while
// the source falls behind, skips forward when it catches up, and reports
// both. What ffrwd/switch did for itself, for any node.
//
//	record hold {
//		anchor: anchor,
//		lead: f64,
//		linger: option<f64>,
//		timeout: option<f64>,
//		group: option<string>,
//		port-param: option<string>,
//	}
type Hold struct {
	_      cm.HostLayout `json:"-"`
	Anchor Anchor        `json:"anchor"`

	// Seconds ahead of the clock a first-frame start is scheduled.
	Lead float64 `json:"lead"`

	// Seconds the last frame stays after the source ends; none drops it
	// at once.
	Linger cm.Option[float64] `json:"linger"`

	// Seconds of programme time without a frame before a live source is
	// given up on and its feed ended; none waits for it.
	Timeout cm.Option[float64] `json:"timeout"`

	// Hold inputs of one group arrive on one connection from one source
	// (a feeder's picture and sound): one offset, fixed by the group's
	// first picture, and feed starts and ends on the same tick.
	Group cm.Option[string] `json:"group"`

	// The param that carries this input's loopback port. Bound to a
	// stream, the host writes the port it picked there; left unbound, the
	// host listens on the port the call wrote, and whatever connects is
	// the source.
	PortParam cm.Option[string] `json:"port-param"`
}

// Interval represents the record "ffrwd:av/node-types@0.19.0#interval".
//
// A message input paired by time: every message whose pts falls in the
// tick's interval, extended by `ahead`, each delivered once at the first
// tick that holds it, held while it is ahead of the clock. The host
// settles the interval once the producer's progress has passed its end
// plus `ahead`; `latency` bounds that wait, and a message later than the
// bound is delivered at the next tick and reported.
//
//	record interval {
//		latency: option<f64>,
//		ahead: f64,
//	}
type Interval struct {
	_ cm.HostLayout `json:"-"`
	// The most this input waits, in seconds: the interval settles once the
	// clock input has arrived this long past its end, progress or not.
	// None waits for the producer's progress alone; a producer that sends
	// none (a lateral, a data feeder) needs a bound set.
	Latency cm.Option[float64] `json:"latency"`

	// Seconds past the interval's end whose messages are handed with it,
	// for a node that acts before a stamp (a fade in before a cue).
	Ahead float64 `json:"ahead"`
}

// Pairing represents the variant "ffrwd:av/node-types@0.19.0#pairing".
//
//	variant pairing {
//		lockstep,
//		hold(hold),
//		interval(interval),
//		arrival,
//	}
type Pairing cm.Variant[uint8, HoldShape, Hold]

// PairingLockstep returns a [Pairing] of case "lockstep".
//
// The clock's pts exactly: same source, one frame per tick. The input
// `clock` names is declared lockstep.
func PairingLockstep() Pairing {
	var data struct{}
	return cm.New[Pairing](0, data)
}

// Lockstep returns true if [Pairing] represents the variant case "lockstep".
func (self *Pairing) Lockstep() bool {
	return self.Tag() == 0
}

// PairingHold returns a [Pairing] of case "hold".
//
// Frame kinds only.
func PairingHold(data Hold) Pairing {
	return cm.New[Pairing](1, data)
}

// Hold returns a non-nil *[Hold] if [Pairing] represents the variant case "hold".
func (self *Pairing) Hold() *Hold {
	return cm.Case[Hold](self, 1)
}

// PairingInterval returns a [Pairing] of case "interval".
//
// Message kinds only.
func PairingInterval(data Interval) Pairing {
	return cm.New[Pairing](2, data)
}

// Interval returns a non-nil *[Interval] if [Pairing] represents the variant case "interval".
func (self *Pairing) Interval() *Interval {
	return cm.Case[Interval](self, 2)
}

// PairingArrival returns a [Pairing] of case "arrival".
//
// Delivered as it arrives, unpaired: packets to a sink, data a node
// orders itself.
func PairingArrival() Pairing {
	var data struct{}
	return cm.New[Pairing](3, data)
}

// Arrival returns true if [Pairing] represents the variant case "arrival".
func (self *Pairing) Arrival() bool {
	return self.Tag() == 3
}

var _PairingStrings = [4]string{
	"lockstep",
	"hold",
	"interval",
	"arrival",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Pairing) String() string {
	return _PairingStrings[v.Tag()]
}

// Accepts represents the record "ffrwd:av/node-types@0.19.0#accepts".
//
// What an input accepts. Empty lists accept anything of the kind.
//
//	record accepts {
//		pixel-formats: list<string>,
//		sample-formats: list<string>,
//		sample-rates: list<u32>,
//		channel-counts: list<u32>,
//		codecs: list<string>,
//		wants: wants,
//		like: option<string>,
//	}
type Accepts struct {
	_             cm.HostLayout   `json:"-"`
	PixelFormats  cm.List[string] `json:"pixel-formats"`
	SampleFormats cm.List[string] `json:"sample-formats"`
	SampleRates   cm.List[uint32] `json:"sample-rates"`
	ChannelCounts cm.List[uint32] `json:"channel-counts"`
	Codecs        cm.List[string] `json:"codecs"`
	Wants         Wants           `json:"wants"`

	// Conformed by the host to that input's stream: a video to its size,
	// an audio to its rate and layout. The named input is single.
	Like cm.Option[string] `json:"like"`
}

// InputPort represents the record "ffrwd:av/node-types@0.19.0#input-port".
//
//	record input-port {
//		name: string,
//		kind: port-kind,
//		required: bool,
//		many: bool,
//		pairing: pairing,
//		rows: rows-use,
//		window: u32,
//		stride: u32,
//		accepts: accepts,
//		schema: option<string>,
//	}
type InputPort struct {
	_        cm.HostLayout `json:"-"`
	Name     string        `json:"name"`
	Kind     PortKind      `json:"kind"`
	Required bool          `json:"required"`

	// Any number of streams bound to this one port, each with its own
	// metadata and time base (a publisher's renditions, a weave's rows
	// inputs).
	Many    bool    `json:"many"`
	Pairing Pairing `json:"pairing"`
	Rows    RowsUse `json:"rows"`

	// The clock input: frames (video) or samples (audio) a call sees, and
	// how many it consumes. Every other input hands the tick's interval
	// and declares 1/1.
	Window  uint32  `json:"window"`
	Stride  uint32  `json:"stride"`
	Accepts Accepts `json:"accepts"`

	// Data inputs: the JSON schema of the rows the node reads here, as
	// `rows-module` declared its input rows. None accepts any row.
	Schema cm.Option[string] `json:"schema"`
}

// LikeInput represents the record "ffrwd:av/node-types@0.19.0#like-input".
//
// An input's format with one field overridden: a matte the size of its
// picture, in gray. The named input is single and a frame kind.
//
//	record like-input {
//		port: string,
//		pixel-format: option<string>,
//		sample-format: option<string>,
//	}
type LikeInput struct {
	_            cm.HostLayout     `json:"-"`
	Port         string            `json:"port"`
	PixelFormat  cm.Option[string] `json:"pixel-format"`
	SampleFormat cm.Option[string] `json:"sample-format"`
}

// OutputFormat represents the variant "ffrwd:av/node-types@0.19.0#output-format".
//
//	variant output-format {
//		video(video-format),
//		audio(audio-format),
//		data(string),
//		packets(coded-stream),
//		like(like-input),
//	}
type OutputFormat cm.Variant[uint8, CodedStreamShape, CodedStream]

// OutputFormatVideo returns a [OutputFormat] of case "video".
func OutputFormatVideo(data VideoFormat) OutputFormat {
	return cm.New[OutputFormat](0, data)
}

// Video returns a non-nil *[VideoFormat] if [OutputFormat] represents the variant case "video".
func (self *OutputFormat) Video() *VideoFormat {
	return cm.Case[VideoFormat](self, 0)
}

// OutputFormatAudio returns a [OutputFormat] of case "audio".
func OutputFormatAudio(data AudioFormat) OutputFormat {
	return cm.New[OutputFormat](1, data)
}

// Audio returns a non-nil *[AudioFormat] if [OutputFormat] represents the variant case "audio".
func (self *OutputFormat) Audio() *AudioFormat {
	return cm.Case[AudioFormat](self, 1)
}

// OutputFormatData returns a [OutputFormat] of case "data".
//
// The codec, "json" today.
func OutputFormatData(data string) OutputFormat {
	return cm.New[OutputFormat](2, data)
}

// Data returns a non-nil *[string] if [OutputFormat] represents the variant case "data".
func (self *OutputFormat) Data() *string {
	return cm.Case[string](self, 2)
}

// OutputFormatPackets returns a [OutputFormat] of case "packets".
func OutputFormatPackets(data CodedStream) OutputFormat {
	return cm.New[OutputFormat](3, data)
}

// Packets returns a non-nil *[CodedStream] if [OutputFormat] represents the variant case "packets".
func (self *OutputFormat) Packets() *CodedStream {
	return cm.Case[CodedStream](self, 3)
}

// OutputFormatLike returns a [OutputFormat] of case "like".
func OutputFormatLike(data LikeInput) OutputFormat {
	return cm.New[OutputFormat](4, data)
}

// Like returns a non-nil *[LikeInput] if [OutputFormat] represents the variant case "like".
func (self *OutputFormat) Like() *LikeInput {
	return cm.Case[LikeInput](self, 4)
}

var _OutputFormatStrings = [5]string{
	"video",
	"audio",
	"data",
	"packets",
	"like",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v OutputFormat) String() string {
	return _OutputFormatStrings[v.Tag()]
}

// OutputPort represents the record "ffrwd:av/node-types@0.19.0#output-port".
//
//	record output-port {
//		name: string,
//		kind: port-kind,
//		format: option<output-format>,
//		time-base: option<rational>,
//		latency: f64,
//		schema: option<string>,
//		row: option<u32>,
//	}
type OutputPort struct {
	_    cm.HostLayout `json:"-"`
	Name string        `json:"name"`
	Kind PortKind      `json:"kind"`

	// None: the clock input's format, as most filters leave it.
	Format cm.Option[OutputFormat] `json:"format"`

	// None: the clock input's.
	TimeBase cm.Option[Rational] `json:"time-base"`

	// How far behind the end of its tick's interval a stamp may fall, in
	// seconds; 0 when everything leaves with its tick. A window's
	// length is not counted here: a recogniser that emits a window's
	// results with the window declares 0. Consumers pairing by interval
	// and the compiler's delay sums read it.
	Latency float64 `json:"latency"`

	// Data outputs: the JSON schema of the rows this port writes.
	Schema cm.Option[string] `json:"schema"`

	// A source read in FROM: the row of `relation` this output belongs
	// to. Outputs of one row are one rendition.
	Row cm.Option[uint32] `json:"row"`
}

// Clock represents the variant "ffrwd:av/node-types@0.19.0#clock".
//
//	variant clock {
//		input(string),
//		rate(rational),
//		rate-of(string),
//		self-clocked,
//	}
type Clock cm.Variant[uint8, string, string]

// ClockInput returns a [Clock] of case "input".
func ClockInput(data string) Clock {
	return cm.New[Clock](0, data)
}

// Input returns a non-nil *[string] if [Clock] represents the variant case "input".
func (self *Clock) Input() *string {
	return cm.Case[string](self, 0)
}

// ClockRate returns a [Clock] of case "rate".
//
// A generator: ticks at this rate, paced to real time in a live run
// and as fast as the outputs drain otherwise. For a node with inputs
// that only need turns (a publisher's network session): at least this
// often, and the last call comes once every input has ended, unless
// the node finished first.
func ClockRate(data Rational) Clock {
	return cm.New[Clock](1, data)
}

// Rate returns a non-nil *[Rational] if [Clock] represents the variant case "rate".
func (self *Clock) Rate() *Rational {
	return cm.Case[Rational](self, 1)
}

// ClockRateOf returns a [Clock] of case "rate-of".
//
// A rate clock at the named input's rate, which the compiler reads
// off that port's first stream; the input itself is held like any
// other. A tile of pictures at the first picture's rate.
func ClockRateOf(data string) Clock {
	return cm.New[Clock](2, data)
}

// RateOf returns a non-nil *[string] if [Clock] represents the variant case "rate-of".
func (self *Clock) RateOf() *string {
	return cm.Case[string](self, 2)
}

// ClockSelfClocked returns a [Clock] of case "self-clocked".
//
// The node emits when it has something; its outputs' pts are the
// timeline (a network source).
func ClockSelfClocked() Clock {
	var data struct{}
	return cm.New[Clock](3, data)
}

// SelfClocked returns true if [Clock] represents the variant case "self-clocked".
func (self *Clock) SelfClocked() bool {
	return self.Tag() == 3
}

var _ClockStrings = [4]string{
	"input",
	"rate",
	"rate-of",
	"self-clocked",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Clock) String() string {
	return _ClockStrings[v.Tag()]
}

// NodeShape represents the record "ffrwd:av/node-types@0.19.0#node-shape".
//
//	record node-shape {
//		inputs: list<input-port>,
//		outputs: list<output-port>,
//		clock: clock,
//		pure: bool,
//		one-to-one: bool,
//		bounded: bool,
//		relation: list<string>,
//	}
type NodeShape struct {
	_       cm.HostLayout       `json:"-"`
	Inputs  cm.List[InputPort]  `json:"inputs"`
	Outputs cm.List[OutputPort] `json:"outputs"`
	Clock   Clock               `json:"clock"`

	// Every call depends only on what it was handed, counting a state
	// input's earlier rows as handed. A host spreads a pure node over
	// workers; an impure one runs as one instance, in order.
	Pure bool `json:"pure"`

	// Frame kinds: one frame out per frame in on the clock's outputs, each at
	// its tick's pts. Audio: samples conserved and contiguous.
	OneToOne bool `json:"one-to-one"`

	// A rate or self-clocked node: whether it ends by itself. A live one
	// does not, and the compiler plans it as live. Ignored on an input
	// clock.
	Bounded bool `json:"bounded"`

	// A source read in FROM: one JSON object per relation row (rendition,
	// bandwidth, codecs, geometry), which its outputs name by index.
	Relation cm.List[string] `json:"relation"`
}

// BoundStream represents the record "ffrwd:av/node-types@0.19.0#bound-stream".
//
// One stream bound to an input port at `init`.
//
//	record bound-stream {
//		port: string,
//		id: u32,
//		info: stream-info,
//		format: option<output-format>,
//		rendition: rendition-meta,
//		row: option<u32>,
//		decode-delay: u32,
//		latency: option<f64>,
//	}
type BoundStream struct {
	_    cm.HostLayout `json:"-"`
	Port string        `json:"port"`

	// Names the stream for the instance's life: distinct across the
	// bound streams, and what every tick call and `same` take.
	ID uint32 `json:"id"`

	// Its time base is `info.time-base`.
	Info StreamInfo `json:"info"`

	// The format the stream arrives in, resolved: never `like`. Packets
	// inputs carry `coded`.
	Format    cm.Option[OutputFormat] `json:"format"`
	Rendition RenditionMeta           `json:"rendition"`

	// The relation row the stream came from, where the call reads rows (a
	// sink handed a ladder); the publisher names its tracks by it.
	Row cm.Option[uint32] `json:"row"`

	// Packets inputs: how deep the stream reorders, as `input-stream`
	// carries it at 0.18. 0 elsewhere.
	DecodeDelay uint32 `json:"decode-delay"`

	// Data inputs: the producer's declared latency, when it has one.
	Latency cm.Option[float64] `json:"latency"`
}

// Message represents the record "ffrwd:av/node-types@0.19.0#message".
//
//	record message {
//		pts: s64,
//		data: list<u8>,
//	}
type Message struct {
	_    cm.HostLayout  `json:"-"`
	Pts  int64          `json:"pts"`
	Data cm.List[uint8] `json:"data"`
}

// TimedRows represents the record "ffrwd:av/node-types@0.19.0#timed-rows".
//
//	record timed-rows {
//		pts: s64,
//		rows: list<string>,
//	}
type TimedRows struct {
	_    cm.HostLayout   `json:"-"`
	Pts  int64           `json:"pts"`
	Rows cm.List[string] `json:"rows"`
}

// FeedStart represents the record "ffrwd:av/node-types@0.19.0#feed-start".
//
//	record feed-start {
//		tags: list<tuple<string, string>>,
//		first-pts: s64,
//		at: s64,
//	}
type FeedStart struct {
	_ cm.HostLayout `json:"-"`
	// The source's tags, `smart_timed` among them.
	Tags cm.List[[2]string] `json:"tags"`

	// Its first frame's pts, in its own time base.
	FirstPts int64 `json:"first-pts"`

	// The clock time that first frame stands at, in the clock's time base:
	// what maps the source's pts onto the tick.
	At int64 `json:"at"`
}

// Feed represents the record "ffrwd:av/node-types@0.19.0#feed".
//
// A hold input's feed: one source, from the tick its first frame shows
// on to the last its last frame shows on, `linger` included. The source
// going backwards, or forwards by more than a second, ends it and
// starts the next.
//
//	record feed {
//		start: feed-start,
//		ends: option<s64>,
//	}
type Feed struct {
	_     cm.HostLayout `json:"-"`
	Start FeedStart     `json:"start"`

	// The clock time of the last tick its last frame shows on, once the
	// host can foretell it: the source ended, or timed out.
	Ends cm.Option[int64] `json:"ends"`
}

// Frame represents the record "ffrwd:av/node-types@0.19.0#frame".
//
// One frame as a tick sees it, without its bytes: a picture, or the
// tick's audio samples as one run, which is a frame as codecs count
// them.
//
//	record frame {
//		pts: s64,
//		index: u32,
//		duration: option<s64>,
//		rows: list<string>,
//	}
type Frame struct {
	_ cm.HostLayout `json:"-"`
	// In the stream's time base; for audio, the first sample's.
	Pts int64 `json:"pts"`

	// Its place in the stream's `frames` this tick, oldest first from 0:
	// what `fetch` and `same` name it by.
	Index uint32 `json:"index"`

	// How long it is presented, in the stream's time base; none where
	// nothing settles it.
	Duration cm.Option[int64] `json:"duration"`

	// The rows that arrived with it, each a JSON object from an upstream
	// module. Empty on an input whose `rows` is `ignore`.
	Rows cm.List[string] `json:"rows"`
}
